### ISSUE TITLE
Problem in RPM "%post"

### ISSUE THREAD

**Issue by fromdualjb** [codership/galera#222]
Oli's bug report (number 4 in his counting):
<pre>
shell> yum install galera-3

Running Transaction
  Installing : galera-3-25.3.9.rc1-4.1.x86_64                                      4/5 
Non-fatal POSTIN scriptlet failure in rpm package galera-3-25.3.9.rc1-4.1.x86_64
/var/tmp/rpm-tmp.t7CXDG: line 1: fg: no job control
warning: %post(galera-3-25.3.9.rc1-4.1.x86_64) scriptlet failed, exit status 1
  Cleanup    : openssl-1.0.0-27.el6_4.2.x86_64                                     5/5 
</pre>

My analysis:
According to the following page, current code (= just one macro call) is wrong:
https://en.opensuse.org/openSUSE:Packaging_Conventions_RPM_Macros#.25fillup_and_insserv
Spec file needs this directive (missing), without it the macro "%fillup_and_insserv" (used in the "%post" section) will not work:
PreReq: %insserv_prereq %fillup_prereq

**Comment by philip-galera** [comment]
As discussed in Skype lets try to use a pull request to deliver the patch to galera. Therefore, assigning it back to Joerg.

**Comment by philip-galera** [comment]
Merged.
