### ISSUE TITLE
A lot of strange errors on CentOS7

### ISSUE THREAD

**Issue by shinguz** [codership/galera#224]
No clue how to fix these!

service mysql start
Starting MySQL.... ERROR! The server quit without updating PID file (/var/lib/mysql/centos7tpl.rebenweg.pid).

2015-02-09 21:35:52 2953 [Warning] WSREP: access file(gvwstate.dat) failed(No such file or directory)

2015-02-09 21:35:52 2953 [ERROR] WSREP: Permission denied
2015-02-09 21:35:52 2953 [ERROR] WSREP: failed to open gcomm backend connection: 13: error while trying to listen 'tcp://0.0.0.0:4567?socket.non_blocking=1', asio error 'Permission denied': 13 (Permission denied)
         at gcomm/src/asio_tcp.cpp:listen():777
2015-02-09 21:35:52 2953 [ERROR] WSREP: gcs/src/gcs_core.cpp:long int gcs_core_open(gcs_core_t*, const char*, const char*, bool)():206: Failed to open backend connection: -13 (Permission denied)
2015-02-09 21:35:52 2953 [ERROR] WSREP: gcs/src/gcs.cpp:long int gcs_open(gcs_conn_t*, const char*, const char*, bool)():1379: Failed to open channel 'my_wsrep_cluster' at 'gcomm://': -13 (Permission denied)
2015-02-09 21:35:52 2953 [ERROR] WSREP: gcs connect failed: Permission denied
2015-02-09 21:35:52 2953 [ERROR] WSREP: wsrep::connect() failed: 7
2015-02-09 21:35:52 2953 [ERROR] Aborting

**Comment by shinguz** [comment]
Update on this: when I start the mysqld WITHOUT service:
/usr/sbin/mysqld --user=mysql
it seems to start. So this looks like it is upstart or init script related.

**Comment by shinguz** [comment]
/etc/init.d/mysql start
Starting MySQL.... ERROR! The server quit without updating PID file (/var/lib/mysql/centos7tpl.rebenweg.pid).
mysqld_safe &
[1] 3587
[root@centos7tpl mysql]# 150209 22:02:18 mysqld_safe Logging to '/var/lib/mysql/centos7tpl.rebenweg.err'.
--> this seems to work

**Comment by shinguz** [comment]
[root@centos7tpl mysql]# systemctl start mysql 
Job for mysql.service failed. See 'systemctl status mysql.service' and 'journalctl -xn' for details.


[root@centos7tpl mysql]# systemctl status mysql.service
mysql.service - LSB: start and stop MySQL
   Loaded: loaded (/etc/rc.d/init.d/mysql)
   Active: failed (Result: exit-code) since Mon 2015-02-09 22:05:17 CET; 8s ago
  Process: 3824 ExecStart=/etc/rc.d/init.d/mysql start (code=exited, status=1/FAILURE)

Feb 09 22:05:13 centos7tpl.rebenweg systemd[1]: Starting LSB: start and stop MySQL...
Feb 09 22:05:17 centos7tpl.rebenweg mysql[3824]: Starting MySQL.... ERROR! The server quit without updating PID file (/var/lib/mysql/centos7tpl.rebenweg.pid).
Feb 09 22:05:17 centos7tpl.rebenweg systemd[1]: mysql.service: control process exited, code=exited status=1
Feb 09 22:05:17 centos7tpl.rebenweg systemd[1]: Failed to start LSB: start and stop MySQL.
Feb 09 22:05:17 centos7tpl.rebenweg systemd[1]: Unit mysql.service entered failed state.


[root@centos7tpl mysql]# journalctl -xn
-- Logs begin at Mon 2015-02-09 21:30:17 CET, end at Mon 2015-02-09 22:05:17 CET. --
Feb 09 22:01:53 centos7tpl.rebenweg dbus-daemon[418]: dbus[418]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop
Feb 09 22:01:53 centos7tpl.rebenweg systemd[1]: Starting Network Manager Script Dispatcher Service...
-- Subject: Unit NetworkManager-dispatcher.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit NetworkManager-dispatcher.service has begun starting up.
Feb 09 22:01:53 centos7tpl.rebenweg dbus-daemon[418]: dbus[418]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Feb 09 22:01:53 centos7tpl.rebenweg dbus[418]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Feb 09 22:01:53 centos7tpl.rebenweg systemd[1]: Started Network Manager Script Dispatcher Service.
-- Subject: Unit NetworkManager-dispatcher.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit NetworkManager-dispatcher.service has finished starting up.
-- 
-- The start-up result is done.
Feb 09 22:05:13 centos7tpl.rebenweg systemd[1]: Starting LSB: start and stop MySQL...
-- Subject: Unit mysql.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mysql.service has begun starting up.
Feb 09 22:05:17 centos7tpl.rebenweg mysql[3824]: Starting MySQL.... ERROR! The server quit without updating PID file (/var/lib/mysql/centos7tpl.rebenweg.pid).
Feb 09 22:05:17 centos7tpl.rebenweg systemd[1]: mysql.service: control process exited, code=exited status=1
Feb 09 22:05:17 centos7tpl.rebenweg systemd[1]: Failed to start LSB: start and stop MySQL.
-- Subject: Unit mysql.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mysql.service has failed.
-- 
-- The result is failed.
Feb 09 22:05:17 centos7tpl.rebenweg systemd[1]: Unit mysql.service entered failed state.

**Comment by temeo** [comment]
Have you tried to disable selinux?

**Comment by shinguz** [comment]
yes. worked around the problem. keep it for next package release.

**Comment by philip-galera** [comment]
I am closing this as we have a separate ticket open to provide proper selinux integration.

https://github.com/codership/mysql-wsrep/issues/59

I think selinux support needs to be added to the mysql-wsrep package, as from within the mysqld are ports being opened . So it is a mysql-wsrep and not a galera issue.
