### ISSUE TITLE
socket.ssl_ca undocumented

### ISSUE THREAD

**Issue by grooverdan** [codership/galera#256]
ref: b320a293e9a037d4baa7b74d6c039512ca8e43f0

missing from pages galeraparameters and ssl

**Comment by kennethpjdyer** [comment]
Thanks.  Working on fixes now.  They'll go out in the next site update.

**Comment by grooverdan** [comment]
missed socket.ssl_password_file

**Comment by grooverdan** [comment]
reminder ^

**Comment by ayurchen** [comment]
Dan, what is the meaning of this unassignment^^^ ?

**Comment by grooverdan** [comment]
that ssl_passsword_file isn't documented - at least here https://github.com/codership/documentation/blob/master/galeracluster/source/sslconfig.rst

**Comment by grooverdan** [comment]
and i've no idea how or why this was unassigned. wasn't deliberate.

**Comment by grooverdan** [comment]
fix as per codership/documentation/issues/28 anyway
