### ISSUE TITLE
garbd segfaults when not run as a service and given a configuration file

### ISSUE THREAD

**Issue by rwdalpe** [codership/galera#259]
On CentOS 6 kernel `2.6.32-504.16.2.el6.x86_64`

`garbd` presents the following behavior:

Given the following configuration file

```
address = "omitted:4567 omitted:4567"
group = "forums"
name = "garbd20"
log = "/cluster/garbd_nodes/20/garbd.log"
options = "gmcast.listen_addr=tcp://0.0.0.0:20001"
```

When attempting to run `garbd` from the command line (even as root) with the following command

```
garbd -d -c garbd.cfg
```

The program immedately segfaults with nothing written to the log.

In `/var/log/messages` the following line is written

```
kernel: garbd[1315]: segfault at fffffffffffffff8 ip 0000000000428b95 sp 00007fff57d9c698 error 6 in garbd[400000+1c4000]
```

Running garbd **without** the configuration file, by explicitly writing

```
garbd -d -a gcomm://omitted:4567,omitted:4567 -g forums -o gmcast.listen_addr=tcp://0.0.0.0:20001 -n garbd20 -l /cluster/garbd_nodes/20/garbd.log
```

Works with no issues. Even if the configuration file and all parent directories are given world read and execute privileges, the segfault still occurs.

Output of `yum info galera`

```
Installed Packages
Name        : galera
Arch        : x86_64
Version     : 25.3.9
Release     : 1.rhel6.el6
Size        : 38 M
Repo        : installed
From repo   : mariadb
Summary     : Galera: a synchronous multi-master wsrep provider (replication engine)
URL         : http://www.codership.com/
License     : GPL-2.0
Description : Galera is a fast synchronous multimaster wsrep provider (replication engine)
```

**Comment by ayurchen** [comment]
I could not get a segfault on my system, but abort due to unhandled exception - sure. The problem with the config file is:
1. values are quoted as per MySQL tradition. Boost program options don't understand that.
2. address value is wrong. It should be exactly like on a command line (since it is the same parameter)

**Comment by rwdalpe** [comment]
@ayurchen thank you for the response and the commit to address the issue.

I originally had the address in the same form as the command line parameter. I recently changed it to be consistent with this documentation, which shows the form I have written here: http://galeracluster.com/documentation-webpages/arbitrator.html. Neither form worked as expected with the configuration file.

If it matters for investigation, at some point in the past the config file method was working correctly. Unfortunately I'm not sure exactly when it stopped working or what update caused it to break. Tomorrow I might be able to look and see what updates that system underwent recently.

Thanks again!

**Comment by ayurchen** [comment]
Thanks for notifying. This is an error in documentation: https://github.com/codership/documentation/issues/72
Notice that address parameter to grabd binary and the same parameter to garbd service scirpt are different formats. (That's yet another bug)
