### ISSUE TITLE
Package does not install on Debian Jesse -  libboost-program-options1.54.0 but it is not installable

### ISSUE THREAD

**Issue by philip-galera** [codership/galera#264]
The galera-3-arbitrator package that we began building for Debian Jessie fails to install on a Jessie minimal VM:

```
The following packages have unmet dependencies:
 galera-arbitrator-3 : Depends: libboost-program-options1.54.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Package is available from here:

http://repos.codership.com/testing/debian/pool/main/g/galera-3/

**Comment by philip-galera** [comment]
Teemu tracked this to multiple libboost packages installed in the Docker container. Recreating the container all the way from scratch fixed the problem.

**Comment by ghost** [comment]
@philip-galera Is this issue fixed? I'm still having the same issue. 😞
