### ISSUE TITLE
Installing the galera-arbitrator package should not cause the service to start automatically.

### ISSUE THREAD

**Issue by philip-galera** [codership/galera#266]
Currently, the garb service will start automatically when installing the galera-arbitrator package. However, the service can not properly start before the configuration file has been modified to include a list of existing Galera nodes.

Therefore, the service should not start when the package is installed. The mysql-wsrep package also does not start the mysqld service upon installation, as it also requires additional configuration.

**Comment by ottok** [comment]
In issue mysql-wsrep#82 mysqld was inhibited from starting automatically on install. I'll do the same changes for the garbd daemon too.

**Comment by philip-galera** [comment]
Debian Jessie is now using systemd so any upstart-specific fixes may not be enough.

**Comment by ottok** [comment]
Interesting discussion by Riak developers: https://gist.github.com/lusis/1721727

I tested that simply changing the filename to .disabled does not work like it did with the upstart script in mysql-wsrep. I am now testing the `dh_installinit -n` option.

**Comment by ottok** [comment]
Fixed now:

```
$ sudo apt-get install galera-arbitrator-3
Get:1 http://labs.seravo.fi/~otto/mariadb-repo/ galera-sid-amd64/ galera-arbitrator-3 25.3.6-1 [507 kB]
Selecting previously unselected package galera-arbitrator-3.
(Reading database ... 58193 files and directories currently installed.)
Preparing to unpack .../galera-arbitrator-3_25.3.6-1_amd64.deb ...
Unpacking galera-arbitrator-3 (25.3.6-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up galera-arbitrator-3 (25.3.6-1) ...

$ dpkg -L galera-arbitrator-3 
/.
/etc
/etc/init.d
/etc/init.d/garb
/etc/default
/etc/default/garb
/usr
/usr/share
/usr/share/man
/usr/share/man/man8
/usr/share/man/man8/garbd.8.gz
/usr/share/doc
/usr/share/doc/galera-arbitrator-3
/usr/share/doc/galera-arbitrator-3/changelog.Debian.gz
/usr/share/doc/galera-arbitrator-3/copyright
/usr/bin
/usr/bin/garbd

$ sudo service garb start
[FAIL] List of GALERA_NODES is not configured ... failed!
```
