### ISSUE TITLE
Current 3.x head does not build in Debian Sid on i386

### ISSUE THREAD

**Issue by ottok** [codership/galera#274]
I noticed that current development head fails to build on Debian Sid (unstable) on i386 with the error:

```
g++ -o gcache/src/gcache_mem_store.o -c -Wno-long-long -Wno-deprecated -ansi -pipe -Weffc++ -Wold-style-cast -g -O3 -DNDEBUG -m32 -march=i686 -Wall -Wextra -Wno-unused-parameter -pedantic -D_FORTIFY_SOURCE=2 -pthread -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -Werror -Igalerautils/src gcache/src/gcache_mem_store.cpp
gcache/src/gcache_page_store.cpp: In member function 'void* gcache::PageStore::malloc_new(unsigned int)':
gcache/src/gcache_page_store.cpp:209:30: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         new_page (page_size_ > size ? page_size_ : size);
                              ^
cc1plus: all warnings being treated as errors
scons: *** [gcache/src/gcache_page_store.o] Error 1
```

Full log at http://labs.seravo.fi/~otto/mariadb-repo/galera-sid-i386/galera_25.3.6-1_i386.build-22f7f8f-pbuilder.log

I have done multiple builds and it is repeatable.

In March the 3.x development branch didn't have any issues. Successful log visible at http://labs.seravo.fi/~otto/mariadb-repo/galera-sid-i386/galera-3_25.3.6-1_amd64.build-8cb779e-pbuilder.log

Current Debian Sid on amd64 builds OK. Build log at http://labs.seravo.fi/~otto/mariadb-repo/galera-sid-amd64/galera_25.3.6-1_amd64.build-22f7f8f-pbuilder.log

Current stable release 25.3.10 builds OK in Debian sid on both i386 and amd64. See logs at http://labs.seravo.fi/~otto/mariadb-repo/galera-3-sid-i386/galera-3_25.3.10-1_amd64.build-f9e69ba-pbuilder.log and http://labs.seravo.fi/~otto/mariadb-repo/galera-3-sid-amd64/galera-3_25.3.10-1_amd64.build-f9e69ba-pbuilder.log

Therefore I conclude that this issue is very specific regarding the platform and version, as described in the title.

**Comment by philip-galera** [comment]
Seems like the function definition was changed recently:

aafd799f (Alexey Yurchenko   2015-04-15 02:13:56 +0300 203) gcache::PageStore::malloc_new (unsigned int size)

So Assigning to Alex.

**Comment by philip-galera** [comment]
Relevant commit:

```
commit aafd799f680e35801e3c6268e80a37ed654974af
Author: Alexey Yurchenko <ayurchen@gmail.com>
Date:   Wed Apr 15 02:13:56 2015 +0300

    Travis CI support plus
      - fixes compilation with clang, including a few changes in the code which this version of clang didn't like
      - does away with galerautils.hpp header to minimize includes
      - other compilation cleanups
      - switches GCache malloc interface from ssize_t to int since it should be identical on both 64 and 32-bit systems
```

**Comment by philip-galera** [comment]
GCC is probably 4.9.2

**Comment by ottok** [comment]
Yes, latest GCC in Debian unstable is 4.9.2 (https://packages.debian.org/sid/gcc)

**Comment by philip-galera** [comment]
Pushed.

**Comment by ottok** [comment]
I confirm it works now on all platforms I build for:

```
[to 28.5.2015 10.39.50 +0300] Building galera sid-amd64 at commit fee4160
[to 28.5.2015 11.07.29 +0300] Uploaded galera sid-amd64
[to 28.5.2015 11.07.52 +0300] Building galera sid-i386 at commit fee4160
[to 28.5.2015 11.35.15 +0300] Uploaded galera sid-i386
[to 28.5.2015 11.35.21 +0300] Building galera jessie-amd64 at commit fee4160
[to 28.5.2015 12.03.08 +0300] Uploaded galera jessie-amd64
[to 28.5.2015 12.03.17 +0300] Building galera jessie-i386 at commit fee4160
[to 28.5.2015 12.32.07 +0300] Uploaded galera jessie-i386
[to 28.5.2015 12.32.13 +0300] Building galera trusty-amd64 at commit fee4160
[to 28.5.2015 12.57.31 +0300] Uploaded galera trusty-amd64
[to 28.5.2015 12.57.37 +0300] Building galera trusty-i386 at commit fee4160
[to 28.5.2015 13.22.46 +0300] Uploaded galera trusty-i386
[to 28.5.2015 13.22.52 +0300] Building galera precise-amd64 at commit fee4160
[to 28.5.2015 13.47.54 +0300] Uploaded galera precise-amd64
```

**Comment by philip-galera** [comment]
Glad to hear. We have pushed all fixes for 32-bit compatibility that we had in both galera and mysql-wsrep.
