### ISSUE TITLE
Potential integer overflow in GCache

### ISSUE THREAD

**Issue by ayurchen** [codership/galera#275]
Signed ints are used to handle buffer sizes in GCache, While GCache is not supposed to handle buffers bigger than 2GB, internally buffer sizes have header which adds to the size, so in extreme cases, when GCache is passed size between `(2GB - header_size, 2GB]`, there will be an overflow. I don't even want to think what will happen in this case.

To avoid it, at least unsigned ints must be used internally.

Also, store sizes (ring buffer, pages) must be at least `size_t` (maximum that can be mmapped)

**Comment by philip-galera** [comment]
Pushed.
