### ISSUE TITLE
Insert on duplicate key update error

### ISSUE THREAD

**Issue by ValeDale** [codership/galera#295]
When we execute queries like 

> ```
> INSERT into table (col1, col2, col3) values(value1, value2, value3) ON DUPLICATE KEY UPDATE
> ```

Always  abort and throw the next error message:

> ```
> ERROR 1213 (40001): Deadlock found when trying to get lock; try restarting transaction
> ```

The only way to execute this kind of query is inside a transaction.

Moreover, when we execute these queries in MySQL (without Galera WSREP), are processed without problems.

Our MySQL Galera cluster has 4 nodes with versions: Server version: 5.5.37-log MySQL Community Server (GPL), wsrep_25.10.r3990

**Comment by philip-galera** [comment]
Hello,

Thank you for reporting the issue. Can you please try increasing the wsrep_retry_autocommit variable to 3 and see if it increases the percentage of successful queries? This will help us pin-point the source of the problem.

**Comment by philip-galera** [comment]
I am unable to reproduce this issue. A test case with INSERT ON DUPLICATE KEY UPDATE will be added to our test suite.

If you have any additional information or observations please feel free to reopen the ticket.
