### ISSUE TITLE
Command-line option missing to start node in isolation (rolling upgrade, ...)

### ISSUE THREAD

**Issue by fromdualjb** [codership/galera#311]
According to mail from Seppo, some upgrades (when done rolling) require the node to be started in isolation (he mentioned it for MySQL 5.5 -> 5.6, for the "mysql_upgrade" run).

I did not find a parameter for "service mysql start ..." that would do this:
- The manual mentions "--wsrep-on=off", but this does not produce the effect (the node still joins the cluster).
- I tried "--wsrep-provider=none", but "mysqld_safe" will not pass this onwards to "mysqld".

I achieved this effect by calling "mysqld ..... --wsrep-provider=none" directly, but this cannot be recommended: It blocks the terminal, and the daemon can only be stopped by "mysqladmin shutdown" (or by a signal), it is no service any more.

Proposed changes:
- Modify "mysqld_safe" such that it will pass "--wsrep-provider=none" onwards to "mysqld".
- Document this as the way to start a node in isolation.
- Fix the discrepancy between code and documentation regarding  "--wsrep-on=off".

Limitation:
A mechanism for systemctl is still needed (like already for "--bootstrap").

**Comment by philip-galera** [comment]
The problem with --wsrep-provider option not being passed to mysqld has been separated into ticket https://github.com/codership/mysql-wsrep/issues/165

**Comment by philip-galera** [comment]
The issue with --wsrep-on=OFF having no effect has been separated into ticket https://github.com/codership/mysql-wsrep/issues/166

I am closing this ticket as it was filed under the wrong project. Please subscribe to the two new tickets.
