### ISSUE TITLE
Galera fails to build with config stage not finding pthread in Debian Sid

### ISSUE THREAD

**Issue by ottok** [codership/galera#321]
In Debian Sid (unstable) builds fail on some platforms because in the configure stage scons complains that if cannot find the pthread library:

```
dh build-arch
   dh_testdir -a
   dh_auto_configure -a
   debian/rules override_dh_auto_build
make[1]: Entering directory '/«PKGBUILDDIR»'
-j 2 tests=1
scons -j 2 tests=1
scons: Reading SConscript files ...
Host: linux s390x 64bit
Signature: version: 3.10, revision: 8182fa6
Checking for C library pthread... no
Error: pthread library not found
make[1]: *** [override_dh_auto_build] Error 1
```

Full log example at https://buildd.debian.org/status/fetch.php?pkg=galera-3&arch=s390x&ver=25.3.10-1&stamp=1438104927
Builds overview page: https://buildd.debian.org/status/package.php?p=galera-3
Platforms affected: arm64, armel, armhf, mips, mipsel, powerpc, ppc64el, s390x 

I suspect this is related to the GCC 4.9 -> GCC 5.0 transition in Debian Sid.

For reference, here is a list of phtread libraries available in Debian as separate packages: https://packages.debian.org/search?keywords=pthread&searchon=names&suite=all&section=all

**Comment by ottok** [comment]
This also applies to many unofficial Debian platforms: alpha, hppa, ppc64 and x32
Overview at: http://buildd.debian-ports.org/status/package.php?p=galera-3

**Comment by ayurchen** [comment]
Otto, is it possible to see `config.log` from build root for at least one of these builds? It contains the actual issue. (maybe dumping it to stderr in case of build failure is a good idea?)

**Comment by ottok** [comment]
Not at the moment. I'll try to get access to some of these build platforms. If you have a Raspberry Pie you could be able to reproduce the build yourself too.

**Comment by ottok** [comment]
@ayurchen config.log from a powerpc machine with Debian Sid:

```
$ cat config.log 
file /home/otto/galera-3-25.3.10/SConstruct,line 247:
    Configure(confdir = .sconf_temp)
scons: Configure: Checking for C library pthread... 
.sconf_temp/conftest_0.c <-
  |
  |
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
gcc -o .sconf_temp/conftest_0.o -c -std=c99 -fno-strict-aliasing -pipe -g -O3 -DNDEBUG -m32 -march=i686 -Wall -Wextra -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -pthread -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -I. -Iasio -Icommon -Igalerautils/src -Igcomm/src -Igcomm/src/gcomm -Igcache/src -Igcs/src -Iwsdb/src -Igalera/src .sconf_temp/conftest_0.c
gcc: error: unrecognized command line option '-march=i686'
scons: Configure: no
```

**Comment by ottok** [comment]
Does this contain anything useful?

```
(sid_powerpc-dchroot)otto@partch:~/galera-3-25.3.10$ gcc -dumpspecs | grep pthread
                              %{!shared:                                    %{!pg:                        %{!pthread:-lc}                                 %{pthread:-lc_r}}                             %{pg:                 %{!pthread:-lc_p}                               %{pthread:-lc_r_p}}                         }
%{mnewlib: --start-group -llinux -lc --end-group } %{!mnewlib: %{pthread:-lpthread} %{shared:-lc} %{!shared: %{profile:-lc_p} %{!profile:-lc}}}
%{!shared:%{pthread:-lpthread%{p:_p}%{!p:%{pg:_p}}}} %{!shared:-lc%{p:_p}%{!p:%{pg:_p}}}
-D__unix__ -D__gnu_linux__ -D__linux__ %{!undef:                                %{!ansi:                                  %{!std=*:-Dunix -D__unix -Dlinux -D__linux}                 %{std=gnu*:-Dunix -D__unix -Dlinux -D__linux}}}         -Asystem=linux -Asystem=unix -Asystem=posix %{pthread:-D_REENTRANT}
%{posix:-D_POSIX_SOURCE} %{pthread:-D_POSIX_THREADS}
%{!fsyntax-only:%{!c:%{!M:%{!MM:%{!E:%{!S:    %(linker) %{!fno-use-linker-plugin:%{!fno-lto:     -plugin %(linker_plugin_file)     -plugin-opt=%(lto_wrapper)     -plugin-opt=-fresolution=%u.res     %{!nostdlib:%{!nodefaultlibs:%:pass-through-libs(%(link_gcc_c_sequence))}}     }}%{flto|flto=*:%<fcompare-debug*}     %{flto} %{fno-lto} %{flto=*} %l %{pie:-pie} %{fuse-ld=*:-fuse-ld=%*}  %{gz*:%e-gz is not supported in this configuration} %X %{o*} %{e*} %{N} %{n} %{r}    %{s} %{t} %{u*} %{z} %{Z} %{!nostdlib:%{!nostartfiles:%S}} %{!nostdlib:%{fvtable-verify=std: -lvtv -u_vtable_map_vars_start -u_vtable_map_vars_end}    %{fvtable-verify=preinit: -lvtv -u_vtable_map_vars_start -u_vtable_map_vars_end}}     %{static:} %{L*} %(mfwrap) %(link_libgcc) %{!nostdlib:%{!nodefaultlibs:%{%:sanitize(address):%{!shared:libasan_preinit%O%s} %{static-libasan:%{!shared:-Bstatic --whole-archive -lasan --no-whole-archive -Bdynamic}}%{!static-libasan:-lasan}}     %{%:sanitize(thread):%{static-libtsan:%{!shared:-Bstatic --whole-archive -ltsan --no-whole-archive -Bdynamic}}%{!static-libtsan:-ltsan}}     %{%:sanitize(leak):%{static-liblsan:%{!shared:-Bstatic --whole-archive -llsan --no-whole-archive -Bdynamic}}%{!static-liblsan:-llsan}}}} %o         %{fopenacc|fopenmp|ftree-parallelize-loops=*:%:include(libgomp.spec)%(link_gomp)}    %{fcilkplus:%:include(libcilkrts.spec)%(link_cilkrts)}    %{fgnu-tm:%:include(libitm.spec)%(link_itm)}    %(mflib)  %{fsplit-stack: --wrap=pthread_create}    %{fprofile-arcs|fprofile-generate*|coverage:-lgcov} %{!nostdlib:%{!nodefaultlibs:%{%:sanitize(address): %{static-libasan:%:include(libsanitizer.spec)%(link_libasan)}    %{static:%ecannot specify -static with -fsanitize=address}}    %{%:sanitize(thread): %{static-libtsan:%:include(libsanitizer.spec)%(link_libtsan)}    %{static:%ecannot specify -static with -fsanitize=thread}}    %{%:sanitize(undefined):%{static-libubsan:-Bstatic} -lubsan %{static-libubsan:-Bdynamic} %{static-libubsan:%:include(libsanitizer.spec)%(link_libubsan)}}    %{%:sanitize(leak): %{static-liblsan:%:include(libsanitizer.spec)%(link_liblsan)}}}}     %{!nostdlib:%{!nodefaultlibs:%(link_ssp) %(link_gcc_c_sequence)}}    %{!nostdlib:%{!nostartfiles:%E}} %{T*} }}}}}}
```

**Comment by ayurchen** [comment]
Otto, offending compiler option is `-march=i686` which seems to be set for any 32-bit machine in the old SConscript, regardless of the actual architecture. https://github.com/codership/galera/commit/22c4a52b3c22ad8f81defe3925f9f220408cd4ec should fix the issue for PPC and s390x at least.
Scons prints diagnostic like 'Host: linux s390x 64bit' at the beginning of every build. If you could send me these lines (or links to build logs) from all the offending architectures, I could cook in support for those. Sorry, we don't have access to anything but x86 ATM.

**Comment by ottok** [comment]
Builds overview page is at https://buildd.debian.org/status/package.php?p=galera-3
It has links to all build logs.

Note that sometimes builds are cross-built, so we should perhaps not solely rely on checking the host CPU, because in cross-compilations we have different host and target CPUs. It is good that you have the platform definition as a compiler option so that the builder can choose whatever target they want.

**Comment by ayurchen** [comment]
Otto, could you please try this commit https://github.com/codership/galera/commit/a3d5eed8b7da0082f6e5f9deab7774bf0189e38d or gh321 branch? If still some builds fail, is it possible to get config.log from those?

**Comment by philip-galera** [comment]
a3d5eed is now in main 3.x branch. The gh321 branch has been deleted.

**Comment by ottok** [comment]
@ayurchen the commit/patch https://github.com/codership/galera/commit/a3d5eed8b7da0082f6e5f9deab7774bf0189e38d.patch didn't apply cleanly

```
Applying patch backported-pthread-platform-fix.patch
patching file SConstruct
Hunk #1 succeeded at 23 with fuzz 2.
Hunk #2 FAILED at 87.
Hunk #3 succeeded at 255 (offset 17 lines).
1 out of 3 hunks FAILED -- rejects in file SConstruct
patching file galerautils/src/SConscript
Hunk #1 succeeded at 33 (offset -6 lines).
```

I probably need to apply multiple commits, which ones? Or should I just wait for 25.3.11 to be released?

**Comment by ottok** [comment]
OK, I backported #328 in commit https://github.com/ottok/galera-3/commit/eeab3bbc2b30488c2bd8bda5ff4f2db772921925

**Comment by ottok** [comment]
Now the pthread error is present even on i386 platforms, see log:
https://launchpadlibrarian.net/215617038/buildlog_ubuntu-wily-i386.galera-3_25.3.10-2~wily1~1440602536.eeab3bb_BUILDING.txt.gz

```
make[1]: Entering directory '/«PKGBUILDDIR»'
# Print build env info to help debug builds on different platforms
dpkg-architecture
DEB_BUILD_ARCH=i386
DEB_BUILD_ARCH_BITS=32
DEB_BUILD_ARCH_CPU=i386
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=i686
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=i686-linux-gnu
DEB_BUILD_MULTIARCH=i386-linux-gnu
DEB_HOST_ARCH=i386
DEB_HOST_ARCH_BITS=32
DEB_HOST_ARCH_CPU=i386
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=i686
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=i686-linux-gnu
DEB_HOST_MULTIARCH=i386-linux-gnu
DEB_TARGET_ARCH=i386
DEB_TARGET_ARCH_BITS=32
DEB_TARGET_ARCH_CPU=i386
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=i686
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=i686-linux-gnu
DEB_TARGET_MULTIARCH=i386-linux-gnu
-j 4 tests=1
scons -j 4 tests=1
scons: Reading SConscript files ...
Host: linux i686 32bit
Signature: version: 3.10, revision: 8182fa6
Checking for C library pthread... no
Error: pthread library not found
```

Before this "fix" it did build on i386 just fine, see old log: 
https://launchpadlibrarian.net/212360288/buildlog_ubuntu-wily-i386.galera-3_25.3.10-1~wily1~1437600933.35a49c7_BUILDING.txt.gz

```
make[1]: Entering directory '/«PKGBUILDDIR»'
-j 4 tests=1
scons -j 4 tests=1
scons: Reading SConscript files ...
Host: linux i686 32bit
Signature: version: 3.10, revision: 8182fa6
Checking for C library pthread... yes
Checking for C library rt... yes
Checking for C header file sys/epoll.h... yes
Checking for C header file byteswap.h... yes
```

Ideas what is going on?

Here is the commit log if you want to see all the changes I did: https://github.com/ottok/galera-3/commits/master

**Comment by ayurchen** [comment]
Otto, we need `config.log` from the source root directory, this is where scons writes actual results. Perhaps running scons like
`scons -j 4 tests=1 || cat config.log`
would post it to the log outputs at https://buildd.debian.org/status/package.php?p=galera-3&suite=sid
so we could see all of them at once.

Note that this is not a actually a pthread-related issue, but what they call "compiler cannot create executables" - bad options passed to compiler/linker.

**Comment by ottok** [comment]
@ayurchen Here you go:
1. Failed i386 build with config.log output: https://launchpadlibrarian.net/215646992/buildlog_ubuntu-wily-i386.galera-3_25.3.10-2~wily1~1440623631.4f6e37b_BUILDING.txt.gz
1. Successful amd64 build with config.log output: https://launchpadlibrarian.net/215647291/buildlog_ubuntu-wily-amd64.galera-3_25.3.10-2~wily1~1440623631.4f6e37b_BUILDING.txt.gz

Please note that you should not be too eager to auto-detect the build environment, because in cross-building cases you would rather want to follow scons flags about the build target than any direct info about the host machine running the build. In Debian builds we have all the DEB_ variables available and we could in debian/rules pass some of them to scons if it helps.

**Comment by ayurchen** [comment]
On 2015-08-27 00:31, Otto Kekäläinen wrote:

> Please note that you should not be too eager to auto-detect the build 
> environment, because in cross-building cases you would rather want to 
> follow scons flags about the build target than any direct info about 
> the host machine running the build.

That's what is happening - this is what scons detected and what we use:

Host: linux i686 32bit

However somehow it still tries to build 64bit tests (see -m64):

gcc -o .sconf_temp/conftest_0.o -c -std=c99 -fno-strict-aliasing -pipe 
-g -O3 -DNDEBUG -m64 -Wall -Wextra -Wno-unused-parameter 
-D_FORTIFY_SOURCE=2 -pthread -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -I. 
-Iasio -Icommon -Igalerautils/src -Igcomm/src -Igcomm/src/gcomm 
-Igcache/src -Igcs/src -Iwsdb/src -Igalera/src .sconf_temp/conftest_0.c

So far I don't see how it is possible.

**Comment by Esysteme** [comment]
I got the same problem on Banana Pi (ARM v7)

[Node1][21:12]root@bananapi:~/galera$ ./scripts/build.sh
~/galera ~/galera
~/galera
scons: Reading SConscript files ...
Host: linux armv7l 32bit
Signature: version: 3.10, revision: 3468
Checking for C library pthread... no
Error: pthread library not found

any idea how to fix it ?

**Comment by ayurchen** [comment]
Otto, I can see that Debian package auto-building still attempts to build Galera 3.10. Is it possible to switch it to 3.12, now that it has been released? It fixes some of the problems (like __PRETTY_FUNCTION) and would eliminate possible errors in back patching.

**Comment by ottok** [comment]
I've been trying to upload 3.12 since a week http://anonscm.debian.org/cgit/pkg-mysql/galera-3.git/commit/?id=7bc79949737843ded596978eaa6c233a75c9153c but I have some permission struggles..

**Comment by ottok** [comment]
Ok, upload was completed successfully now. The new code includes more debugging options, that is the printing of DEB_\* build environment variables and the config.log output.

Unfortunately now it seems all platforms suffer from the pthread not found issue:

```
make[1]: Entering directory '/«PKGBUILDDIR»'
# Print build env info to help debug builds on different platforms
dpkg-architecture
DEB_BUILD_ARCH=arm64
DEB_BUILD_ARCH_BITS=64
DEB_BUILD_ARCH_CPU=arm64
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=aarch64
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=aarch64-linux-gnu
DEB_BUILD_MULTIARCH=aarch64-linux-gnu
DEB_HOST_ARCH=arm64
DEB_HOST_ARCH_BITS=64
DEB_HOST_ARCH_CPU=arm64
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=aarch64
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=aarch64-linux-gnu
DEB_HOST_MULTIARCH=aarch64-linux-gnu
DEB_TARGET_ARCH=arm64
DEB_TARGET_ARCH_BITS=64
DEB_TARGET_ARCH_CPU=arm64
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=aarch64
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=aarch64-linux-gnu
DEB_TARGET_MULTIARCH=aarch64-linux-gnu
-j 6 tests=1
scons -j 6 tests=1 || touch FAIL # Print config.log if build fails
scons: Reading SConscript files ...
Host: linux aarch64 64bit
Signature: version: 3.12, revision: 9921e73
Checking for C library pthread... no
Error: pthread library not found
*****************************************
**  config.log contents for debugging  **
*****************************************
file /«PKGBUILDDIR»/SConstruct,line 226:
    Configure(confdir = .sconf_temp)
scons: Configure: Checking for C library pthread... 
.sconf_temp/conftest_0.c <-
  |
  |
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
gcc -o .sconf_temp/conftest_0.o -c -std=c99 -fno-strict-aliasing -pipe -g -O3 -DNDEBUG -mtune=native -Wall -Wextra -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -pthread -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H .sconf_temp/conftest_0.c
.sconf_temp/conftest_0.c:1:0: error: unknown value 'native' for -mtune

 ^
scons: Configure: no

*****************************************
if [ -f FAIL ]; then exit 1; fi
make[1]: *** [override_dh_auto_build] Error 1
debian/rules:28: recipe for target 'override_dh_auto_build' failed
make[1]: Leaving directory '/«PKGBUILDDIR»'
make: *** [build-arch] Error 2
debian/rules:48: recipe for target 'build-arch' failed
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2
```

See build status at https://buildd.debian.org/status/package.php?p=galera-3

PS. You can easily get armhf access for 2,99 €/month at scaleway.com if you want to try builds on a non-intel platform.

**Comment by ayurchen** [comment]
Cool! Now we are actually getting much farther - with the exception of few systems that don't recognize -mtune=native option, most get to compilation and fail in ./chromium/build_config.h. Puzzling result for s390x though.

> PS. You can easily get armhf access for 2,99 €/month at scaleway.com if you want to try builds on a non-intel platform.

Thanks, will check it out.

**Comment by ayurchen** [comment]
Otto,
After closer investigation, debian builds failed for four main reasons:
- not all platforms supported option -mtune=native
- some platforms complained about uninitialized data in random seed generator
- some platforms were undefined in chromium/build_config.h
- the rest failed due to new link dependencies of libcheck introduced in Sid
  
  please check this commit: https://github.com/codership/galera/commit/f87972c0f14f947fa646485565774034e2771760 - it addresses all of the above issues.

x32 is an exception, will address it later.

**Comment by ayurchen** [comment]
Otto, this commit https://github.com/codership/galera/commit/0bcbaabc9f6ca55823b76cb4ed3f5d3c83c306df (should be directly applicable on top of https://github.com/codership/galera/commit/f87972c0f14f947fa646485565774034e2771760) should fix x32 compilation as well.

**Comment by ottok** [comment]
A patch was posted in Debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799150#20

**Comment by ottok** [comment]
In my pbuilder environment (chroot and cross-building) i386 builds fail with:

```
Error: pthread library not found
*****************************************
**  config.log contents for debugging  **
*****************************************
file /tmp/buildd/galera-3-25.3.12/SConstruct,line 222:
    Configure(confdir = .sconf_temp)
scons: Configure: Checking for C library pthread... 
.sconf_temp/conftest_0.c <-
  |
  |
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
gcc -o .sconf_temp/conftest_0.o -c -std=c99 -fno-strict-aliasing -pipe -g -O3 -DNDEBUG -mx32 -Wall -Wextra -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -pthread -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H .sconf_temp/conftest_0.c
gcc -o .sconf_temp/conftest_0 -mx32 .sconf_temp/conftest_0.o -lpthread
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: skipping incompatible /usr/lib/gcc/i586-linux-gnu/5/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/i586-linux-gnu/5/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/i586-linux-gnu/5/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/i586-linux-gnu/5/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find crtn.o: No such file or directory
collect2: error: ld returned 1 exit status
scons: Configure: no
```

See full log at http://labs.seravo.fi/~otto/mariadb-repo/logs/galera-3/galera-3_25.3.12-2_sid_i386_pbuilder.build

This is a regression because in the past (see commit numbers in logs) the i386 builds did work: http://labs.seravo.fi/~otto/mariadb-repo/galera-3-sid-i386/
(Commit ID numbers are from the Debian repo)

i386 builds on other build systems do work.

**Comment by ayurchen** [comment]
I see. Then the last commit (https://github.com/codership/galera/commit/0bcbaabc9f6ca55823b76cb4ed3f5d3c83c306df, attempt to fix x32 build) is wrong.

**Comment by ottok** [comment]
I uploaded new version, looking much better now, thanks!
https://buildd.debian.org/status/package.php?p=galera-3

**Comment by ottok** [comment]
All main platforms build correctly in Debian: https://buildd.debian.org/status/package.php?p=galera-3
Closing this pthread issue now.
