### ISSUE TITLE
bootstrap runtime is not working as mentioned in doc

### ISSUE THREAD

**Issue by sknaik** [codership/galera#326]
Hello,

The runtime changing of a node to primary is not working as mentioned in the document.

mysql> SET GLOBAL wsrep_provider_options='pc.boostrap=1';

ERROR 1210 (HY000): Incorrect arguments to SET

And the mentioned bootstrap option is not present in wsrep_provider_options variable.

I am using the latest version of galera mysql packages which come with wsrep.

5.6.23-log MySQL Community Server (GPL), wsrep_25.10

Thanks,
Sknaik

**Comment by jayjanssen** [comment]
Should be

SET GLOBAL wsrep_provider_options='pc.bootstrap=1';

you have 'pc.boostrap'

On Wed, Aug 19, 2015 at 8:32 AM, sknaik notifications@github.com wrote:

> Hello,
> 
> The runtime changing of a node to primary is not working as mentioned in
> the document.
> 
> mysql> SET GLOBAL wsrep_provider_options='pc.boostrap=1';
> 
> ERROR 1210 (HY000): Incorrect arguments to SET
> 
> And the mentioned bootstrap option is not present in
> wsrep_provider_options variable.
> 
> I am using the latest version of galera mysql packages which come with
> wsrep.
> 
> 5.6.23-log MySQL Community Server (GPL), wsrep_25.10
> 
> Thanks,
> SKumar
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codership/galera/issues/326.

## 

Jay Janssen
Managing Consultant, Percona
https://about.me/jay.janssen
