### ISSUE TITLE
Garbd on CentOS 7.1 does not start / configure properly

### ISSUE THREAD

**Issue by seitzbg** [codership/galera#347]
GALERA_NODES="100.65.3.71 100.65.3.72 100.65.3.73 100.65.3.74 100.65.3.75 100.65.11.71 100.65.11.72 100.65.11.73 100.65.11.74 100.65.11.75"

I get:

[unknown] root@p-pop-002-net:/var/log#  /usr/bin/garb-systemd start
Error #487: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
Error #487: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
Error #487: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
Error #487: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
Error #487: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
Error #487: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
Error #487: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
Error #487: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
Error #487: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
Error #487: Your port specifications are illegal.  Example of proper form: "-100,200-1024,T:3000-4000,U:60000-"
QUITTING!
 ERROR! None of the nodes in 100.65.3.71 100.65.3.72 100.65.3.73 100.65.3.74 100.65.3.75 100.65.11.71 100.65.11.72 100.65.11.73 100.65.11.74 100.65.11.75 is accessible

The systemd service script is calling another script (/usr/bin/garb-systemd) which is broken.

Package Version: galera-25.3.9-1.rhel7.el7.centos.x86_64

Please advise.

**Comment by philip-galera** [comment]
Hello, your issue is a duplicate to https://github.com/codership/galera/issues/312

The solution is to add an explicit port number, `:4567` after each IP in the list.

**Comment by ayurchen** [comment]
> Please advise.

Upgrade to latest version ;)
