### ISSUE TITLE
ARMv7 compile issue

### ISSUE THREAD

**Issue by nikolay8601** [codership/galera#359]
scons: Reading SConscript files ...
Host: linux armv7l 32bit
Signature: version: 3.13dev, revision: XXXX
Checking for C library pthread... (cached) yes
Checking for C library atomic... (cached) yes
Checking for C library rt... (cached) yes
Checking for C header file sys/epoll.h... (cached) yes
Checking for C header file byteswap.h... (cached) yes
Checking for C header file endian.h... (cached) yes
Checking for C header file execinfo.h... (cached) yes
Checking for C++ header file boost/shared_ptr.hpp... (cached) yes
Checking for C++ header file unordered_map... (cached) no
Checking for C++ header file tr1/unordered_map... (cached) yes
Checking for C++ library boost_program_options... (cached) yes
Checking for C++ header file asio.hpp... (cached) yes
Checking for C++ header file asio/ssl.hpp... (cached) yes
Checking for C library ssl... (cached) yes
Checking for C library crypto... (cached) yes
Checking for C header file check.h... (cached) yes
Checking for C library check... (cached) yes
Checking for C library m... (cached) yes
Checking for C library subunit... (cached) no
Checking for C library rt... (cached) yes
 -std=c99 -fno-strict-aliasing -pipe
 -g -O3 -DNDEBUG -pthread -Wall -Wextra -Wno-unused-parameter -Werror
 -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -DGCS_USE_GCOMM -DGALERA_LOG_H_ENABLE_CXX -Wno-variadic-macros -Wno-old-style-cast -Wno-missing-field-initializers -Wno-effc++
 -Wno-long-long -Wno-deprecated -ansi -pipe -Weffc++ -Wold-style-cast
scons: done reading SConscript files.
scons: Building targets ...
g++ -o galera/src/certification.o -c -Wno-long-long -Wno-deprecated -ansi -pipe -Weffc++ -Wold-style-cast -g -O3 -DNDEBUG -pthread -Wall -Wextra -Wno-unused-parameter -Werror -pedantic -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -I. -Iasio -Icommon -Igalerautils/src -Igcache/src -Igcs/src galera/src/certification.cpp
In file included from galerautils/src/gu_buffer.hpp:14:0,
                 from galerautils/src/gu_serialize.hpp:33,
                 from galera/src/key_os.hpp:11,
                 from galera/src/write_set.hpp:9,
                 from galera/src/trx_handle.hpp:9,
                 from galera/src/certification.hpp:8,
                 from galera/src/certification.cpp:5:
./boost/shared_ptr.hpp:32:14: error: 'boost::shared_ptr' has not been declared
 using boost::shared_ptr;
              ^
In file included from galerautils/src/gu_serialize.hpp:33:0,
                 from galera/src/key_os.hpp:11,
                 from galera/src/write_set.hpp:9,
                 from galera/src/trx_handle.hpp:9,
                 from galera/src/certification.hpp:8,
                 from galera/src/certification.cpp:5:
galerautils/src/gu_buffer.hpp:20:13: error: 'shared_ptr' in namespace 'boost' does not name a type
     typedef boost::shared_ptr<Buffer> SharedBuffer;
             ^
galera/src/certification.cpp: In destructor 'galera::Certification::~Certification()':
galera/src/certification.cpp:858:70: error: 'for_each' was not declared in this scope
     for_each(trx_map_.begin(), trx_map_.end(), PurgeAndDiscard(_this));
                                                                      ^
galera/src/certification.cpp: In member function 'void galera::Certification::assign_initial_position(wsrep_seqno_t, int)':
galera/src/certification.cpp:885:9: error: 'for_each' is not a member of 'std'
         std::for_each(trx_map_.begin(), trx_map_.end(), PurgeAndDiscard(_this));
         ^
galera/src/certification.cpp:893:9: error: 'for_each' is not a member of 'std'
         std::for_each(cert_index_.begin(), cert_index_.end(),
         ^
galera/src/certification.cpp:895:9: error: 'for_each' is not a member of 'std'
         std::for_each(cert_index_ng_.begin(), cert_index_ng_.end(),
         ^
galera/src/certification.cpp:897:9: error: 'for_each' is not a member of 'std'
         std::for_each(trx_map_.begin(), trx_map_.end(),
         ^
galera/src/certification.cpp: In member function 'wsrep_seqno_t galera::Certification::purge_trxs_upto_(wsrep_seqno_t, bool)':
galera/src/certification.cpp:964:67: error: 'for_each' was not declared in this scope
     for_each(trx_map_.begin(), purge_bound, PurgeAndDiscard(_this));
                                                                   ^
In file included from galera/src/write_set.hpp:9:0,
                 from galera/src/trx_handle.hpp:9,
                 from galera/src/certification.hpp:8,
                 from galera/src/certification.cpp:5:
galera/src/key_os.hpp: In member function 'size_t galera::KeyOS::unserialize(const byte_t_, size_t, size_t)':
galera/src/key_os.hpp:308:5: error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
cc1plus: all warnings being treated as errors
scons: **\* [galera/src/certification.o] Error 1
scons: building terminated because of errors.

After multiple libs missing, I manage to reach this step. Please advise what the root cause is. 
If needed I can provide a machine for testing purposes.

**Comment by ayurchen** [comment]
> ./boost/shared_ptr.hpp:32:14: error: 'boost::shared_ptr' has not been declared
> using boost::shared_ptr;

It is not an ARMv7 issue. It is an issue with your boost installation - it seems to be non-functional.

**Comment by nikolay8601** [comment]
You are correct. The issue was with boost. Seemed like under Ubuntu Trusty it is not fully working for this specific architecture
