### ISSUE TITLE
pc.wait_prim and pc.wait_prim_timeout not real config options

### ISSUE THREAD

**Issue by temeo** [codership/galera#360]
Galera documentation in http://galeracluster.com/documentation-webpages/galeraparameters.html#pc-wait-prim-timeout states that `pc.wait_prim` and `pc.wait_prim_timeout` can be given as parameters in `wsrep_provider_options`. However, according to code

```
    bool wait_prim(
        gu::from_string<bool>(
            uri_.get_option(Conf::PcWaitPrim, Defaults::PcWaitPrim)));

    const gu::datetime::Period wait_prim_timeout(
        gu::from_string<gu::datetime::Period>(
            uri_.get_option(Conf::PcWaitPrimTimeout,
                            Defaults::PcWaitPrimTimeout)));
```

this is not so.

**Comment by tom--** [comment]
Perhaps this also explains why the invalid default value "P30S" for pc.wait_prim_timeout is tolerated. I guess it would otherwise be "PT30S".

**Comment by cofyc** [comment]
hi, when will this be fixed? I need to configure `pc.wait_prim_timeout`.

**Comment by philip-galera** [comment]
Pushed and released.
