### ISSUE TITLE
"libs-compat" will be needed for mysql-wsrep-5.7 on RedHat 7

### ISSUE THREAD

**Issue by fromdualjb** [codership/galera#362]
"libs-compat" is needed to satisfy the requirements of pre-installed applications when the MySQL software is upgraded to a new ABI version of "libmysqlclient.so".
Examples:
1) RedHat 6 brings MySQL 5.1 which has "libmysqlclient.so.16", but both MySQL 5.5 and 5.6 bring
    "libmysqlclient.so.18" so they must be accompanied by a "libs-compat" bringing the old client lib.
2) RedHat 7 brings MySQL (MariaDB) 5.5 which has "libmysqlclient.so.18", so MySQL 5.6 fits directly
    (it also has ABI version 18).

MySQL 5.7 has changed the ABI to version 20, so it will again need a "libs-compat" for RedHat 7.
Docu:
http://mysqlserverteam.com/the-client-library-part-1-the-api-the-whole-api-and-nothing-but-the-api/

**Comment by philip-galera** [comment]
moved to https://github.com/codership/mysql-wsrep/issues/225
