### ISSUE TITLE
Failure to detect invalid wsrep_provider_options

### ISSUE THREAD

**Issue by nirbhayc** [codership/galera#365]
Originally filed as https://mariadb.atlassian.net/browse/MDEV-8953

I had a typo in my configuration for wsrep_provider_options. I had ;pc.weight= instead of ;pc.weight=1.
The server failed to start with only these uninformative errors:
[ERROR]WSREP: non-standard exception
[ERROR]WSREP: wsrep::connect() failed: 8
[ERROR]Aborting
The server should really detect an invalid configuration and indicate what is wrong rather than just fail to start.

**Comment by nirbhayc** [comment]
The server should indeed abort on invalid configuration, but with a better error message.

**Comment by nirbhayc** [comment]
Perhaps can be fixed alongside https://github.com/codership/mysql-wsrep/issues/227.

**Comment by ayurchen** [comment]
I guess this one may be closed as fixed.
