### ISSUE TITLE
Documented "gcache" config contradicts advice, cleanup is missing

### ISSUE THREAD

**Issue by fromdualjb** [codership/galera#373]
Customer is using Galera 3.25 with MySQL 5.6.23:
galera-3-25.3.10-2.el6.x86_64
mysql-wsrep-client-5.6-5.6.23-25.10.el6.x86_64
mysql-wsrep-5.6-5.6.23-25.10.el6.x86_64
mysql-wsrep-server-5.6-5.6.23-25.10.el6.x86_64

Customer followed config example on page "http://galeracluster.com/documentation-webpages/configuration.html":
wsrep_provider_options="gcache.size=300M; gcache.page_size=1G"

"gcache" cleanup doesn't work, 148 gcache pages of 1 GB each have accumulated since Sep 2.
Customer is approaching "disk full" and must take action.

In chat communication, I received this info from Codership:
"The value of page_size parameter does not really matter,
  it just regulates how often file creation/deletion operation happens.
  but it makes little sense to have it bigger than the main cache size."
(which is very plausible to me).
I also was warned against removing gcache pages while the node is running.

Please:
1) Get the config example and that chat advice in sync, they contradict each other.
2) Check whether "size < page_size" may break the automatic cleanup.
3) Document a way for manual cleanup, preferably without taking the node down.

**Comment by ayurchen** [comment]
migrated to codership/documentation#137
