### ISSUE TITLE
Parameter to set nice thread priority for Galera Cluster's threads

### ISSUE THREAD

**Issue by GeoffMontee** [codership/galera#374]
On operating systems that use interrupt-driven network I/O (such as RHEL 7), it is relatively common under very high load for Galera Cluster's threads to be starved of CPU time, which means that they can't handle interrupts quickly enough, which means that some packets get dropped. This leads to timeouts, and busy nodes may get evicted from the cluster.

Switching to busy polling for network I/O handling usually helps.

As another potential fix, would it make sense to add a parameter that controls the nice thread priority of Galera Cluster's threads, so that when configured, Galera Cluster's threads will be more likely to get CPU time when they need it?

**Comment by ayurchen** [comment]
Fixed in 8542fcf9d0ca8f9f27b4b3fb98bc6fa4628a21f4
