### ISSUE TITLE
Cluster crashed with signal 11

### ISSUE THREAD

**Issue by enaumchuk** [codership/galera#376]
Nodes:
Red Hat Enterprise Linux Server release 6.7 (Santiago)

Percona XtraDB Cluster (GPL), Release rel70.1, Revision 938, WSREP version 25.8, wsrep_25.8.r4150
wsrep_provider Galera 3.8(rf6147dd)

3-node cluster

All nodes suddenly crashed with signal 11:

NODE1

22:22:46 UTC - mysqld got signal 11 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.
Please help us make Percona XtraDB Cluster better by reporting any
bugs at https://bugs.launchpad.net/percona-xtradb-cluster

key_buffer_size=8388608
read_buffer_size=1048576
max_used_connections=751
max_threads=100001
thread_count=190
connection_count=157
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 307222699 K bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x7fdbe3867d60
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 7fdf590de998 thread_stack 0x40000
/usr/sbin/mysqld(my_print_stacktrace+0x35)[0x8f97d5]
/usr/sbin/mysqld(handle_fatal_signal+0x4b4)[0x6655c4]
/lib64/libpthread.so.0[0x32cbc0f790]
/usr/sbin/mysqld[0xa00de4]
/usr/sbin/mysqld[0xa98887]
/usr/sbin/mysqld[0xa9cb96]
/usr/sbin/mysqld[0xa9cf19]
/usr/sbin/mysqld[0x9f99b0]
/usr/sbin/mysqld[0x9fa098]
/usr/sbin/mysqld[0x9fa122]
/usr/sbin/mysqld[0x909ec8]
/usr/sbin/mysqld[0x91b59c]
/usr/sbin/mysqld(_Z13ha_commit_lowP3THDbb+0x11a)[0x5a520a]
/usr/sbin/mysqld(_ZN13MYSQL_BIN_LOG6commitEP3THDb+0x449)[0x8b1899]
/usr/sbin/mysqld(_Z15ha_commit_transP3THDbb+0x34f)[0x5a571f]
/usr/sbin/mysqld(_Z12trans_commitP3THD+0x49)[0x78e1d9]
/usr/sbin/mysqld(_Z15wsrep_commit_cbPvjPK14wsrep_trx_metaPbb+0x209)[0x59c759]
/usr/lib64/libgalera_smm.so(_ZN6galera13ReplicatorSMM9apply_trxEPvPNS_9TrxHandleE+0x552)[0x7ff99568a722]
/usr/lib64/libgalera_smm.so(_ZN6galera13ReplicatorSMM11process_trxEPvPNS_9TrxHandleE+0x45)[0x7ff99568edf5]
/usr/lib64/libgalera_smm.so(_ZN6galera15GcsActionSource8dispatchEPvRK10gcs_actionRb+0x2da)[0x7ff99566871a]
/usr/lib64/libgalera_smm.so(_ZN6galera15GcsActionSource7processEPvRb+0x63)[0x7ff995668d33]
/usr/lib64/libgalera_smm.so(_ZN6galera13ReplicatorSMM10async_recvEPv+0x93)[0x7ff995686f63]
/usr/lib64/libgalera_smm.so(galera_recv+0x23)[0x7ff99569dc33]
/usr/sbin/mysqld[0x59de31]
/usr/sbin/mysqld(start_wsrep_THD+0x36e)[0x58484e]
/lib64/libpthread.so.0[0x32cbc07a51]
/lib64/libc.so.6(clone+0x6d)[0x32cb4e89ad]

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0): is an invalid pointer
Connection ID (thread ID): 10441812
Status: NOT_KILLED
# 

NODE2

22:22:46 UTC - mysqld got signal 11 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.
Please help us make Percona XtraDB Cluster better by reporting any
bugs at https://bugs.launchpad.net/percona-xtradb-cluster

key_buffer_size=8388608
read_buffer_size=1048576
max_used_connections=751
max_threads=100001
thread_count=85
connection_count=52
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 307222699 K bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x7f383826bd80
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 7f3a3a179998 thread_stack 0x40000
/usr/sbin/mysqld(my_print_stacktrace+0x35)[0x8f97d5]
/usr/sbin/mysqld(handle_fatal_signal+0x4b4)[0x6655c4]
/lib64/libpthread.so.0[0x38ff40f790]
/usr/sbin/mysqld[0xa00de4]
/usr/sbin/mysqld[0xa98887]
/usr/sbin/mysqld[0xa9cb96]
/usr/sbin/mysqld[0xa9cf19]
/usr/sbin/mysqld[0x9f99b0]
/usr/sbin/mysqld[0x9fa098]
/usr/sbin/mysqld[0x9fa122]
/usr/sbin/mysqld[0x909ec8]
/usr/sbin/mysqld[0x91b59c]
/usr/sbin/mysqld(_Z13ha_commit_lowP3THDbb+0x11a)[0x5a520a]
/usr/sbin/mysqld(_ZN13MYSQL_BIN_LOG6commitEP3THDb+0x449)[0x8b1899]
/usr/sbin/mysqld(_Z15ha_commit_transP3THDbb+0x34f)[0x5a571f]
/usr/sbin/mysqld(_Z12trans_commitP3THD+0x49)[0x78e1d9]
/usr/sbin/mysqld(_Z15wsrep_commit_cbPvjPK14wsrep_trx_metaPbb+0x209)[0x59c759]
/usr/lib64/libgalera_smm.so(_ZN6galera13ReplicatorSMM9apply_trxEPvPNS_9TrxHandleE+0x552)[0x7f547fa69722]
/usr/lib64/libgalera_smm.so(_ZN6galera13ReplicatorSMM11process_trxEPvPNS_9TrxHandleE+0x45)[0x7f547fa6ddf5]
/usr/lib64/libgalera_smm.so(_ZN6galera15GcsActionSource8dispatchEPvRK10gcs_actionRb+0x2da)[0x7f547fa4771a]
/usr/lib64/libgalera_smm.so(_ZN6galera15GcsActionSource7processEPvRb+0x63)[0x7f547fa47d33]
/usr/lib64/libgalera_smm.so(_ZN6galera13ReplicatorSMM10async_recvEPv+0x93)[0x7f547fa65f63]
/usr/lib64/libgalera_smm.so(galera_recv+0x23)[0x7f547fa7cc33]
/usr/sbin/mysqld[0x59de31]
/usr/sbin/mysqld(start_wsrep_THD+0x36e)[0x58484e]
/lib64/libpthread.so.0[0x38ff407a51]
/lib64/libc.so.6(clone+0x6d)[0x38ff0e89ad]

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0): is an invalid pointer
Connection ID (thread ID): 123354
Status: NOT_KILLED
# 

NODE3

22:22:46 UTC - mysqld got signal 11 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.
Please help us make Percona XtraDB Cluster better by reporting any
bugs at https://bugs.launchpad.net/percona-xtradb-cluster

key_buffer_size=8388608
read_buffer_size=1048576
max_used_connections=751
max_threads=100001
thread_count=65
connection_count=32
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 307222699 K bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0xad45b1a0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 7fd0f27ebc38 thread_stack 0x40000
/usr/sbin/mysqld(my_print_stacktrace+0x35)[0x8f97d5]
/usr/sbin/mysqld(handle_fatal_signal+0x4b4)[0x6655c4]
/lib64/libpthread.so.0[0x3257a0f790]
/usr/sbin/mysqld[0xa00de4]
/usr/sbin/mysqld[0xa98887]
/usr/sbin/mysqld[0xa9cb96]
/usr/sbin/mysqld[0xa9cf19]
/usr/sbin/mysqld[0x9f99b0]
/usr/sbin/mysqld[0x9fa098]
/usr/sbin/mysqld[0x9fa122]
/usr/sbin/mysqld[0x909ec8]
/usr/sbin/mysqld[0x91b59c]
/usr/sbin/mysqld(_Z13ha_commit_lowP3THDbb+0x11a)[0x5a520a]
/usr/sbin/mysqld(_ZN13MYSQL_BIN_LOG26process_commit_stage_queueEP3THDS1_+0x60b)[0x8ab37b]
/usr/sbin/mysqld(_ZN13MYSQL_BIN_LOG14ordered_commitEP3THDbb+0x421)[0x8b1331]
/usr/sbin/mysqld(_ZN13MYSQL_BIN_LOG6commitEP3THDb+0x554)[0x8b19a4]
/usr/sbin/mysqld(_Z15ha_commit_transP3THDbb+0x34f)[0x5a571f]
/usr/sbin/mysqld(_Z17trans_commit_stmtP3THD+0x35)[0x78d995]
/usr/sbin/mysqld(_Z21mysql_execute_commandP3THD+0x954)[0x6ea184]
/usr/sbin/mysqld(_Z11mysql_parseP3THDPcjP12Parser_state+0x658)[0x6f0338]
/usr/sbin/mysqld[0x6f0491]
/usr/sbin/mysqld(_Z16dispatch_command19enum_server_commandP3THDPcj+0x19d5)[0x6f2675]
/usr/sbin/mysqld(_Z10do_commandP3THD+0x22b)[0x6f3b5b]
/usr/sbin/mysqld(_Z26threadpool_process_requestP3THD+0xcf)[0x79564f]
/usr/sbin/mysqld[0x797d38]
/usr/sbin/mysqld(pfs_spawn_thread+0x12a)[0xaf38ba]
/lib64/libpthread.so.0[0x3257a07a51]
/lib64/libc.so.6(clone+0x6d)[0x32576e89ad]

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (7fb519befb80): is an invalid pointer
Connection ID (thread ID): 381733513
Status: NOT_KILLED

**Comment by ayurchen** [comment]
Crashed deep in percona's code. Wrong tracker.
