### ISSUE TITLE
Galera ignores gcache.size setting

### ISSUE THREAD

**Issue by enaumchuk** [codership/galera#377]
Was: 
Percona XtraDB Cluster 5.6.21 (GPL), Release rel70.1, Revision 938, WSREP version 25.8, wsrep_25.8.r4150
wsrep_provider_version: Galera 3.8(rf6147dd)

Upgraded to
Percona XtraDB Cluster 5.6.26 (GPL), Release rel74.0, Revision 1, WSREP version 25.12, wsrep_25.12
 wsrep_provider_version: Galera 3.12.2(rf3e626d)

after upgrade all 3 nodes are ignoring wsrep-provider-options setting in my.cnf
wsrep-provider-options="gcache.size=6G"
and set galera.cache to 128M (default)

mysql error log shows this:
"20:26:57 25463 [Note] WSREP: Passing config to GCS: base_dir = /var/lib/mysqllogs; base_host = 10.240.23.101;
base_port = 4567; cert.log_conflicts = ON; debug = no; evs.auto_evict = 0; evs.delay_margin = PT1S;
evs.delayed_keep_period = PT30S; evs.inactive_check_period = PT0.5S; evs.inactive_timeout = PT15S;
evs.join_retrans_period = PT1S; evs.max_install_timeouts = 3; evs.send_window = 4; evs.stats_report_period =
PT1M; evs.suspect_timeout = PT5S; evs.user_send_window = 2; evs.view_forget_timeout = PT24H; gcache.dir =
/var/lib/mysqllogs; gcache.keep_pages_count = 0; gcache.keep_pages_size = 0; gcache.mem_size = 0; gcache.name
= /var/lib/mysqllogs/galera.cache; gcache.page_size = 128M; gcache.size = 128M; gcs.fc_debug = 0;
gcs.fc_factor = 1.0; gcs.fc_limit = 16; gcs.fc_master_slave = no; gcs.max_packet_size = 64500;
gcs.max_throttle = 0.25; gcs.recv_q_hard_limit = 9223372036854775807; gcs.recv_q_soft_limit = 0.25;
gcs.sync_donor = no; gmcast.segment = 0; gmcast.version = 0; pc.announce_timeout = PT3S; pc.checksum = false;
pc.ignor"

**Comment by ayurchen** [comment]
Looking at https://bugs.launchpad.net/bugs/1526028 this can be closed as invalid
