### ISSUE TITLE
Binaries (at least partially) built without Large File Support (LFS)

### ISSUE THREAD

**Issue by ottok** [codership/galera#379]
Garbd and libgalera_smm.so ELF binaries appears to be (partially) built without "Large File Support" (LFS). If so, it may not be able to handle large files or files with large metadata values (ex: inode numbers) correctly.

This was detected by Lintian checks in Debian. For details see
https://lintian.debian.org/tags/binary-file-built-without-LFS-support.html
https://lintian.debian.org/full/pkg-mysql-maint@lists.alioth.debian.org.html#galera-3

The severity is minor. There is no urgency whatsoever to fix this, but I decided to open an issue for QA reasons. You might want to fix this when you have extra time or it you come across users who actually need LFS some day.

**Comment by ayurchen** [comment]
This sounds like a false alarm to me. Any large files that Galera may want to open are mmapped. So we are not interested in opening LARGE files on 32-bit systems. Also ATM even mysqld and libinnodb are built wihthout LFS support so I'm not sure if we want to do anything here as well. Things seem to be working fine, so better not fix it ;)

**Comment by ottok** [comment]
Lintian does not complain about this for latest galera-4 anymore, so apparently it is fixed or mitigated in some way. Now Lintian does however complain about *no-bindnow*, which I filed as #559.

**Comment by ottok** [comment]
Current Lintian status has nothing about this, so closing as fixed/invalid.

> galera-4 26.4.5-1
> galera-4_26.4.5-1+b1_amd64.deb
> No tags.
> 
> galera-4_26.4.5-1.dsc
> P maintainer-manual-page debian/additions/garb-systemd.8
> P package-uses-old-debhelper-compat-version 12
> galera-arbitrator-4_26.4.5-1+b1_amd64.deb
> W systemd-service-file-uses-nobody-or-nogroup lib/systemd/system/garb.service User=nobody
> W systemd-service-file-uses-nobody-or-nogroup lib/systemd/system/garbd.service User=nobody
> I package-supports-alternative-init-but-no-init.d-script lib/systemd/system/garbd.service
> Comment: garbd is intentionally not started automatically upon installation,
> Comment: see https://github.com/codership/galera/issues/266
> O script-in-etc-init.d-not-registered-via-update-rc.d etc/init.d/garb

https://lintian.debian.org/sources/galera-4/26.4.5-1.html
