### ISSUE TITLE
Sign source package releases +  update d/watch file to automatically verify in Debian

### ISSUE THREAD

**Issue by ottok** [codership/galera#380]
Currently source packages are released simply as .tar.gz files at http://releases.galeracluster.com/source/

In addition to the file e.g. http://releases.galeracluster.com/source/galera-3-25.3.13.tar.gz there should in future also be a digital signature file http://releases.galeracluster.com/source/galera-3-25.3.13.tar.gz.asc that can be used to verify that the source file is authentic and untampered (using gpp --verify command).

Sign using the same key as already used to sign the repos (http://releases.galeracluster.com/GPG-KEY-galeracluster.com).

For example MariaDB does this (see ftp://ftp.osuosl.org/pub/mariadb/mariadb-10.0.23/source/mariadb-10.0.23.tar.gz and ftp://ftp.osuosl.org/pub/mariadb/mariadb-10.0.23/source/mariadb-10.0.23.tar.gz.asc). Linux distros like Debian with watch files and uscan use these signature files to automatically check that sources used for builds are authentic.

**Comment by ayurchen** [comment]
Philip, is it in your domain?

**Comment by philip-galera** [comment]
@ottok  this has already been implemented and future releases will use signing. You can see here how the layout of the download directory will be :

http://repos.galeracluster.com/testing/source/

If that is what is expected, please feel free to close the ticket.

**Comment by ottok** [comment]
Testing repos looks good. Please reassign this to me so that I'll finish the Debian part of it after next release.

**Comment by philip-galera** [comment]
All yours, thank you!

**Comment by ottok** [comment]
Signed sources in use now downstream: https://anonscm.debian.org/cgit/pkg-mysql/galera-3.git/commit/?id=83f12c33e2dea4c3e82eb1960f61f3d68bba5fa0

This issue can now be closed as the full chain has now been implemented and is deployed.
