### ISSUE TITLE
GCC 6: error: C++11 requires a space between string literal and macro

### ISSUE THREAD

**Issue by philip-galera** [codership/galera#384]
downstream bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812052

```
This package fails to build with GCC 6.  GCC 6 has not been released
yet, but it's expected that GCC 6 will become the default compiler for
stretch.

Note that only the first error is reported; there might be more.  You
can find a snapshot of GCC 6 in experimental.  To build with GCC 6,
you can set CC=gcc-6 CXX=g++-6 explicitly.

You may be able to find out more about this issue at
https://gcc.gnu.org/gcc-6/changes.html

> sbuild (Debian sbuild) 0.67.0 (26 Dec 2015) on dl580gen9-02.hlinux
...
> g++ -o gcs/src/gcs_fifo_lite.o -c -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wno-long-long -Wno-deprecated -ansi -pipe -Weffc++ -Wold-style-cast -g -O3 -DNDEBUG -m64 -pthread -Wall -Wextra -Wno-unused-parameter -Werror -Wdate-time -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -DGCS_USE_GCOMM -DGALERA_LOG_H_ENABLE_CXX -Wno-variadic-macros -Wno-old-style-cast -Wno-missing-field-initializers -Wno-effc++ -Igalerautils/src -Igcomm/src -Igcache/src gcs/src/gcs_fifo_lite.cpp
> gcs/src/gcs_params.cpp:108:23: error: C++11 requires a space between string literal and macro [-Werror=c++11-compat]
>              gu_error ("%s value out of range [%ld, %ld]: %"PRIi64,
>                        ^
> 
> gcs/src/gcs_params.cpp:136:23: error: C++11 requires a space between string literal and macro [-Werror=c++11-compat]
>              gu_error ("%s value out of range [%"PRIi64", %"PRIi64"]: %"PRIi64,
>                        ^
> 
> gcs/src/gcs_params.cpp:136:55: error: C++11 requires a space between string literal and macro [-Werror=c++11-compat]
>              gu_error ("%s value out of range [%"PRIi64", %"PRIi64"]: %"PRIi64,
>                                                        ^
> 
> gcs/src/gcs_params.cpp:136:66: error: C++11 requires a space between string literal and macro [-Werror=c++11-compat]
>              gu_error ("%s value out of range [%"PRIi64", %"PRIi64"]: %"PRIi64,
>                                                                   ^
> 
```

**Comment by ayurchen** [comment]
oh boy... C++11 is nigh!
Interestingly, GCC4 does not complain about this particular line even with `-std=c++11`

**Comment by ayurchen** [comment]
The easiest workaround seems to explicitly disable the warning with `-Wno-c++11-compat`

GCC4.9.2 understands this option. But it is not clear how far back in time it goes.

**Comment by ayurchen** [comment]
It may also be that it is a bug in the compiler used, as `-ansi` option in C++ context should enforce C++98. There is no reason to check for C++11 compatibility.

**Comment by eworm-de** [comment]
This should be fixed by c46321b.

**Comment by ottok** [comment]
The downstream bug has increased severity as Debian is about to migrate to GCC 6. I'll just wait until next release is out and included commit c46321b and hope it is closed then.

**Comment by ottok** [comment]
GCC 6 compatibility was not fixed in 25.3.17 yet...?

**Comment by eworm-de** [comment]
Version 25.3.17 compiles just fine on Arch Linux (`gcc (GCC) 6.1.1 20160802`) without any extra adjustment. What is your issue?

**Comment by ottok** [comment]
Currenty while trying to build 25.3.17 I get:

```
scons: Building targets ...
g++ -o galera/src/certification.o -c -g -O2 -fdebug-prefix-map=/tmp/buildd/galera-3-25.3.17=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-long-long -Wno-deprecated -ansi -pipe -Weffc++ -Wold-style-cast -g -O3 -DNDEBUG -m64 -pthread -Wall -Wextra -Wno-unused-parameter -Werror -pedantic -Wdate-time -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_SYSTEM_ASIO -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -I. -Icommon -Igalerautils/src -Igcache/src -Igcs/src galera/src/certification.cpp
In file included from gcache/src/gcache_mem_store.hpp:12:0,
                 from gcache/src/GCache.hpp:8,
                 from galera/src/galera_gcs.hpp:18,
                 from galera/src/galera_service_thd.hpp:8,
                 from galera/src/certification.hpp:10,
                 from galera/src/certification.cpp:5:
gcache/src/gcache_limits.hpp:57:18: error: comparison is always true due to limited range of data type [-Werror=type-limits]
         GU_COMPILE_ASSERT(DIFF_MIN <=long_long(MIN_SIZE - MAX_SIZE), min_diff);
         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gcache/src/gcache_mem_store.hpp:12:0,
                 from gcache/src/GCache.hpp:8,
                 from galera/src/galera_gcs.hpp:18,
                 from galera/src/galera_service_thd.hpp:8,
                 from galera/src/certification.hpp:10,
                 from galera/src/certification.cpp:5:
gcache/src/gcache_limits.hpp:57:18: error: comparison is always true due to limited range of data type [-Werror=type-limits]
         GU_COMPILE_ASSERT(DIFF_MIN <=long_long(MIN_SIZE - MAX_SIZE), min_diff);
         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
scons: *** [galera/src/certification.o] Error 1
scons: building terminated because of errors.
```

Full log at: http://labs.seravo.fi/~otto/debian/galera-3-sid-amd64/galera-3_25.3.17-1_amd64.build-25f1bff-pbuilder.FAILED.log

I don't know if this is a GCC 6 issue but I'll file it here anyway. I don't know how to solve it. I need help to patch it so that I can get it uploaded to Debian.

**Comment by ottok** [comment]
I repeated the same build and it worked. It seems the issue above was temporary.

Official build logs for 25.3.17 in Debian at: https://buildd.debian.org/status/package.php?p=galera-3

You can close this issue (I don't have permission to).

**Comment by LiYaHX** [comment]
I have the same problem when build OpenJDK on MacOS Sierra 10.12.6 . How can i solve it please?

**Comment by vasild** [comment]
@LiYaHX which same problem? There are two problems reported above. Can you provide the exact error message with the surrounding context? What does OpenJDK has to do with this?

**Comment by LiYaHX** [comment]
1.  View gcc version
`$ gcc -v`
`Using built-in specs.
COLLECT_GCC=gcc-6
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@6/6.4.0/libexec/gcc/x86_64-apple-darwin16.6.0/6.4.0/lto-wrapper
Target: x86_64-apple-darwin16.6.0
Configured with: ../configure --build=x86_64-apple-darwin16.6.0 --prefix=/usr/local/Cellar/gcc@6/6.4.0 --libdir=/usr/local/Cellar/gcc@6/6.4.0/lib/gcc/6 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-6 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew GCC 6.4.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-nls --enable-multilib
Thread model: posix
gcc version 6.4.0 (Homebrew GCC 6.4.0) `

2. Compile OpenJDK 8
`$ make`
`...`
`jdk8/hotspot/src/share/vm/gc_implementation/g1/concurrentMark.cpp:4506:49: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
 #define G1PPRL_ADDR_BASE_FORMAT    " "PTR_FORMAT"-"PTR_FORMAT`
`...`

Thank you very much. @vasild

**Comment by vasild** [comment]
@LiYaHX looks like a problem in OpenJDK. This is not the place to report OpenJDK issues. Anyways, I guess -Wno-c++11-compat may help, from gcc6 man page:

```
       -Wc++11-compat (C++ and Objective-C++ only)
           Warn about C++ constructs whose meaning differs between ISO C++
           1998 and ISO C++ 2011, e.g., identifiers in ISO C++ 1998 that are
           keywords in ISO C++ 2011.  This warning turns on -Wnarrowing and is
           enabled by -Wall.

```
Or editing jdk8/hotspot/src/share/vm/gc_implementation/g1/concurrentMark.cpp:4506, adding the needed space and submitting your changes to OpenJDK devs.

Good luck!

**Comment by LiYaHX** [comment]
Oh no..., i'm sorry and thank you very very much~~. 👍 😆 

Yeah, I add the space between literal and string macro, but there are too many files to edit all of them. So I consider to set the default mode is gnu++14, but i can't find where to configure it. 

On the other way, the gcc 6's defualt mode is gnu++14 according to its office document, but i can't understand why it is C++11 when i compile OpenJDK in fact. [GCC 6 Release Series
Changes, New Features, and Fixes](https://gcc.gnu.org/gcc-6/changes.html)

**Comment by INotWant** [comment]
> Oh no..., i'm sorry and thank you very very much~~.  
> 
> Yeah, I add the space between literal and string macro, but there are too many files to edit all of them. So I consider to set the default mode is gnu++14, but i can't find where to configure it.
> 
> On the other way, the gcc 6's defualt mode is gnu++14 according to its office document, but i can't understand why it is C++11 when i compile OpenJDK in fact. [GCC 6 Release Series Changes, New Features, and Fixes](https://gcc.gnu.org/gcc-6/changes.html)

I have the same problem when I build openjdk7. Can you tell me how to fix it? Thank you!
