### ISSUE TITLE
WSREP: Bad value for 'socket.ssl_key'

### ISSUE THREAD

**Issue by aensley** [codership/galera#387]
I am attempting to initialize a new MariaDB Galera cluster with SSL-encrypted replication.

I have followed [this guide](http://galeracluster.com/documentation-webpages/sslcert.html) to the letter, specified different details for CA, Server, and Client certificates (I [read there can be issues](https://mariadb.com/kb/en/mariadb/mariadb-ssl-connection-issues/) when they are exactly the same), and placed my certificate files in `/etc/mysql/ssl/`.

``` ShellSession
root@server:/etc/mysql/ssl# openssl verify -CAfile ca-cert.pem server-cert.pem client-cert.pem
server-cert.pem: OK
client-cert.pem: OK
root@server:/etc/mysql/ssl#
```

These are my SSL-related settings:

```
[mysqld]
ssl-ca = /etc/mysql/ssl/ca-cert.pem
ssl-key = /etc/mysql/ssl/server-key.pem
ssl-cert = /etc/mysql/ssl/server-cert.pem
wsrep_provider_options="socket.ssl_key=/etc/mysql/ssl/server-key.pem;socket.ssl_cert=/etc/mysql/ssl/server-cert.pem;socket.ssl_ca=/etc/mysql/ssl/ca-cert.pem;socket.checksum=2;socket.ssl_cipher=AES128-SHA"

[mysql]
ssl-ca = /etc/mysql/ssl/ca-cert.pem
ssl-key = /etc/mysql/ssl/client-key.pem
ssl-cert = /etc/mysql/ssl/client-cert.pem
```

When I try to start my first node with `service mysql start --wsrep-new-cluster`, I get the following errors:

```
2016-02-02 14:01:25 140601166120896 [ERROR] WSREP: Bad value '/etc/mysql/ssl/server-key.pem' for SSL parameter 'socket.ssl_key': : 22 (Invalid argument)
     at galerautils/src/gu_asio.cpp:ssl_prepare_context():148
2016-02-02 14:01:25 140601166120896 [ERROR] WSREP: wsrep::init() failed: 7, must shutdown
2016-02-02 14:01:25 140601166120896 [ERROR] Aborting
```

I [found the code](https://github.com/codership/galera/blob/3.x/galerautils/src/gu_asio.cpp#L124) throwing that error, but it didn't help me find the cause of the issue.

I am using MariaDB 10.1.11 with Galera 25.3.12 on Ubuntu 14.04 x64

I've also [opened a question on ServerFault](http://serverfault.com/q/753571) about this.

Since these are self-signed certificates and easily replaced, I would be open to posting them here if need be. I've already re-generated the certificates twice (for a total of 3 sets), with no change in the error.

**Comment by nirbhayc** [comment]
@aensley : Check if mysqld has sufficient permission to access server-key.pem.

**Comment by aensley** [comment]
Yup. That was it. Unbelievable how I can still miss the simplest things. This fixed the problem for me:

``` ShellSession
root@server:/etc/mysql# chmod 500 /etc/mysql/ssl/
root@server:/etc/mysql# chmod 400 /etc/mysql/ssl/*
root@server:/etc/mysql# chown -R mysql:mysql /etc/mysql/ssl/
```

Thank you, and sorry for taking your time.
