### ISSUE TITLE
Regression: Galera 25.3.14 fails to cross-build for i386 (on amd64)

### ISSUE THREAD

**Issue by ottok** [codership/galera#388]
While preparing the 25.3.14 upload to Debian I noticed that on my own pbuilder/chroot-based builds, the i386 builds fail (cross-building on an amd64 host). At least on 25.3.10 cross-building worked fine, so this is a regression. The builds fail with identical message on both Debian sid and jessie chroots, so it is not build environment version related.

Official Debian builds run on real i386 hardware, so this is not a big issue, but it would be nice if the ability to cross-build would be kept working as it used to.

End of build log:

```
dpkg-source: info: building galera-3 using existing ./galera-3_25.3.14.orig.tar.gz
dpkg-source: info: building galera-3 in galera-3_25.3.14-1.debian.tar.xz
dpkg-source: info: building galera-3 in galera-3_25.3.14-1.dsc
 debian/rules build
dh build
   dh_testdir
   dh_auto_configure
   debian/rules override_dh_auto_build
make[1]: Entering directory '/tmp/buildd/galera-3-25.3.14'
# Print build env info to help debug builds on different platforms
dpkg-architecture
DEB_BUILD_ARCH=i386
DEB_BUILD_ARCH_BITS=32
DEB_BUILD_ARCH_CPU=i386
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=i586
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=i586-linux-gnu
DEB_BUILD_MULTIARCH=i386-linux-gnu
DEB_HOST_ARCH=i386
DEB_HOST_ARCH_BITS=32
DEB_HOST_ARCH_CPU=i386
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=i586
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=i586-linux-gnu
DEB_HOST_MULTIARCH=i386-linux-gnu
DEB_TARGET_ARCH=i386
DEB_TARGET_ARCH_BITS=32
DEB_TARGET_ARCH_CPU=i386
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=i586
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=i586-linux-gnu
DEB_TARGET_MULTIARCH=i386-linux-gnu
-j 4 tests=1
scons -j 4 tests=1 || touch FAIL # Print config.log if build fails
scons: Reading SConscript files ...
Host: linux x86_64 32bit
Signature: version: 3.14, revision: 53b88eb
Checking for C library pthread... no
Error: pthread library not found
*****************************************
**  config.log contents for debugging  **
*****************************************
file /tmp/buildd/galera-3-25.3.14/SConstruct,line 262:
    Configure(confdir = .sconf_temp)
scons: Configure: Checking for C library pthread... 
.sconf_temp/conftest_0.c <-
  |
  |
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
gcc -o .sconf_temp/conftest_0.o -c -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -fno-strict-aliasing -pipe -g -O3 -DNDEBUG -mx32 -pthread -Wall -Wextra -Wno-unused-parameter -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H .sconf_temp/conftest_0.c
gcc -o .sconf_temp/conftest_0 -Wl,-z,relro .sconf_temp/conftest_0.o -lpthread
/usr/bin/ld: i386:x64-32 architecture of input file `.sconf_temp/conftest_0.o' is incompatible with i386 output
/usr/bin/ld: BFD (GNU Binutils for Debian) 2.25 assertion fail ../../bfd/elf32-i386.c:3156
/usr/bin/ld: BFD (GNU Binutils for Debian) 2.25 assertion fail ../../bfd/elf32-i386.c:3156
/usr/bin/ld: BFD (GNU Binutils for Debian) 2.25 assertion fail ../../bfd/elf32-i386.c:3156
/usr/bin/ld: BFD (GNU Binutils for Debian) 2.25 assertion fail ../../bfd/elf32-i386.c:3156
/usr/bin/ld: BFD (GNU Binutils for Debian) 2.25 assertion fail ../../bfd/elf32-i386.c:3156
collect2: error: ld returned 1 exit status
scons: Configure: no

*****************************************
if [ -f FAIL ]; then exit 1; fi
debian/rules:28: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/tmp/buildd/galera-3-25.3.14'
debian/rules:48: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
E: Failed autobuilding of package
I: unmounting /var/cache/ccache filesystem
I: unmounting dev/pts filesystem
I: unmounting run/shm filesystem
I: unmounting proc filesystem
```

Example of old log for a successful build: http://labs.seravo.fi/~otto/mariadb-repo/galera-3-sid-i386/galera-3_25.3.10-1_amd64.build-f9e69ba-pbuilder.log

This seems to have to do with how the configure script detects pthread. Looking at old build logs, 25.3.12 did not fail to build due to this kind of undetected pthread error (but it failed due to other reasons) so something in 25.3.13 introduced this issue.

**Comment by temeo** [comment]
The problem is probably -mx32 flag. According to manpage:

> The -mx32 option sets "int", "long", and pointer types to 32 bits, and generates code for the x86-64 architecture.

Is there a real life need for such a build? IMO we could always build pure 32-bit binaries if 32-bit buildroot is used.

Ping @ayurchen

**Comment by ayurchen** [comment]
Yes, most likely it is the case and commenting it out. IIRC it was introduced to fix Debian's own MX2 build, but probably it was a clueless fix. Since then a much better respect for env. variables was implemented, so this option probably can be just ditched.

**Comment by ayurchen** [comment]
On the other hand, how do we build 32-bit binaries?

**Comment by temeo** [comment]
I don't believe we produce any 32-bit binaries by ourselves.

**Comment by ottok** [comment]
Tested with latest 25.3.22 and all builds are OK
![screenshot from 2017-11-21 12-37-27](https://user-images.githubusercontent.com/668724/33070601-372262d4-cec1-11e7-972f-2c0f140dab3b.png)

This issue can be closed now.

**Comment by ottok** [comment]
Build logs for latest upload to Debian are all green as well (for all official Debian platforms): https://buildd.debian.org/status/package.php?p=galera-3

**Comment by ottok** [comment]
Both i386 and x32 seem to build and pass the test suite at least:
![screenshot from 2017-11-24 10-25-57](https://user-images.githubusercontent.com/668724/33203897-ef25f746-d101-11e7-993d-96b2c9a853e4.png)
