### ISSUE TITLE
Galera 25.3.14 fails to cross-build for armhf (on amd64)

### ISSUE THREAD

**Issue by rvalitov** [codership/galera#392]
# The Problem

Failed to build Galera in pbuilder for armhf (Debian Jessie) on amd64. This issue is probably related to #389 and #388. The last log of the pbuilder output is:

```
gcc -o .sconf_temp/conftest_20.o -c -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -fno-strict-aliasing -pipe -g -O3 -DNDEBUG -pthread -Wall -Wextra -Wno-unused-parameter -Werror -pedantic -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_SYSTEM_ASIO -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP .sconf_temp/conftest_20.c
gcc -o .sconf_temp/conftest_20 -Wl,-z,relro .sconf_temp/conftest_20.o -lpthread -latomic -lrt -lssl -lcrypto -lcheck -lm -lrt
scons: Configure: yes


*****************************************
if [ -f FAIL ]; then exit 1; fi
debian/rules:28: recipe for target 'override_dh_auto_build' failed
```

I checked this [auto-building page](https://buildd.debian.org/status/package.php?p=galera-3&suite=sid) which is available for sid (not for jessie) and found out that the same line _gcc -o .sconf_temp/conftest_20.o_ fails on other architectures, too:
- s390x
- alpha
- m68k
- sparc64

The related screenshot of this auto-building page with marked similar log lines:
![buildd status for galera 3 sid](https://cloud.githubusercontent.com/assets/16267156/13402365/2e425090-df10-11e5-9837-afde8e5c8e82.jpeg)

The full pbuilder log is below:
[galera-log.txt](https://github.com/codership/galera/files/151384/galera-log.txt)
# Building other Galera versions

I could successfully build Galera 2.3.6, however, I face problems building other versions. One of the problems is that all versions of Galera after 2.3.6 and before 2.3.14 have the same _debian/changelog_ file that refers to version 2.3.6. The up-to-date version of this file is required, because it is used by the pbuilder to detect version of the package. So, in order to start a build (pass through the pbuilder's pre-build checks) I had to write the correct version into that file, e.g. _2.3.13-1_ (quilt format) for Galera 2.3.13. After that the compilation of the Galera 2.3.13 finishes successfully, but the build process fails on builder unit tests (the last important lines of the build log):

```
g++ -o galera/tests/galera_check -Wl,-z,relro galera/tests/galera_check.o galera/tests/data_set_check.o galera/tests/key_set_check.o galera$
builder_unit_test(["galera/tests/galera_check.passed"], ["galera/tests/galera_check"])
Running suite(s): DataSet
100%: Checks: 1, Failures: 0, Errors: 0
Running suite(s): KeySet
100%: Checks: 1, Failures: 0, Errors: 0
Running suite(s): WriteSet
100%: Checks: 2, Failures: 0, Errors: 0
Running suite(s): write_set
100%: Checks: 8, Failures: 0, Errors: 0
Running suite(s): trx_handle
100%: Checks: 2, Failures: 0, Errors: 0
Running suite(s): service_thd
100%: Checks: 3, Failures: 0, Errors: 0
Running suite(s): ist
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
100%: Checks: 6, Failures: 0, Errors: 0
Running suite(s): saved_state
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
33%: Checks: 3, Failures: 1, Errors: 1
galera/tests/saved_state_check.cpp:48:E:saved_state:test_unsafe:0: (after this point) Received signal 11 (Segmentation fault)
galera/tests/saved_state_check.cpp:155:F:saved_state:test_corrupt:0: Failure 'uuid == WSREP_UUID_UNDEFINED' occured
Total tests failed: 2
scons: *** [galera/tests/galera_check.passed] Error 1
scons: building terminated because of errors.
debian/rules:28: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
```

The log above was generated using [qemu-user-static (1:2.1+dfsg-12+deb8u5a)](https://packages.debian.org/en/jessie/qemu-user-static) - the default version in Debain Jessie. Then I upgraded this package to [qemu-user-static (1:2.5+dfsg-4~bpo8+1)](https://packages.debian.org/en/jessie-backports/qemu-user-static) using jessie-backports repositories. The build in the newer environment gave similar results:

```
g++ -o galera/tests/galera_check -Wl,-z,relro galera/tests/galera_check.o galera/tests/data_set_check.o galera/tests/key_set_check.o galera$
builder_unit_test(["galera/tests/galera_check.passed"], ["galera/tests/galera_check"])
Running suite(s): DataSet
100%: Checks: 1, Failures: 0, Errors: 0
Running suite(s): KeySet
100%: Checks: 1, Failures: 0, Errors: 0
Running suite(s): WriteSet
100%: Checks: 2, Failures: 0, Errors: 0
Running suite(s): write_set
100%: Checks: 8, Failures: 0, Errors: 0
Running suite(s): trx_handle
100%: Checks: 2, Failures: 0, Errors: 0
Running suite(s): service_thd
100%: Checks: 3, Failures: 0, Errors: 0
Running suite(s): ist
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
100%: Checks: 6, Failures: 0, Errors: 0
Running suite(s): saved_state
33%: Checks: 3, Failures: 1, Errors: 1
galera/tests/saved_state_check.cpp:48:E:saved_state:test_unsafe:0: (after this point) Test timeout expired
galera/tests/saved_state_check.cpp:155:F:saved_state:test_corrupt:0: Failure 'uuid == WSREP_UUID_UNDEFINED' occured
Total tests failed: 2
scons: *** [galera/tests/galera_check.passed] Error 1
scons: building terminated because of errors.
debian/rules:28: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
```

According to [old Galera thread](https://groups.google.com/forum/#!topic/codership-team/ZWwZYG78a6A) on Google Groups this issue is related to timeouts defined for the tests. If the test goes too long (which may happen in VM), then it is considered to be failed. It was suggested to alter the string with _tcase_set_timeout(tc, 120);_ call in file _galera/galera/tests/saved_state_check.cpp_. I tried increasing the value to 1200 and even commenting out this command - no luck in both cases - I got the same errors.
# Building on physical armhf device

Building the Galera 25.3.14 on a real armhf device (under Debian jessie) is successful. So, the issue is related to some tests that don't pass in the VM. Thus, causing to terminate the build process.

**Comment by ayurchen** [comment]
I don't think it has anything to do with timeouts. The log is pretty unequivocal about the cause:

```
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
qemu: Unsupported syscall: 350
```

See response in the following thread: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799115 - it seems that your qemu hasn't yet caught up with the Linux kernel. Perhaps downgrading the kernel version could help.

In any case, provided that the build succeeds on a real hardware, I don't see how it is a Galera issue and not the issue with the hardware emulator.

**Comment by rvalitov** [comment]
Thank you for your reply. I agree that this issue is related with the qemu emulator and not Galera. However, many people use qemu, so I will try to find a solution and post it here, so that other people who face this problem will have a clue how to fix it.

I checked the syscall table, and the syscall number 350 refers to **timerfd_create**. The [qemu git](http://git.qemu.org/?p=qemu.git&a=search&h=HEAD&st=commit&s=timerfd) has commits related to timerfd functionality. I will try to build Galera under qemu version that supports the required syscall.
