### ISSUE TITLE
pc.checksum default value incorrectly documented

### ISSUE THREAD

**Issue by kjoiner069** [codership/galera#404]
The default value of the option pc.checksum was changed to false a while ago but the documentation indicates it is still set to true:

Changelog:
https://github.com/codership/galera/commit/64de3c5f85b82ecff9eb1d4f1cd532abb83f2d60

Docs:
http://galeracluster.com/documentation-webpages/galeraparameters.html#pc-checksum

**Comment by philip-galera** [comment]
Thank you. This has been fixed and the updated documentation will be uploaded to our web site shortly.
