### ISSUE TITLE
Galera incompatible with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by ottok** [codership/galera#407]
Debian unstable will be upgrading to OpenSSL 1.1.0 soon. It seems Galera is incompatible with it. Please update the OpenSSL code to work with the new OpenSSL version.

(Originally reported against galera-3 in Debian at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828306)

**Comment by philip-galera** [comment]
Compilation log:

**Comment by philip-galera** [comment]
https://breakpoint.cc/openssl-1.1-rebuild-2016-05-29/Attempted/galera-3_25.3.15-1_amd64-20160529-1418

**Comment by temeo** [comment]
This does not look like galera specific issue, but rather incompatibility between libasio-dev and openssl 1.1. There seems to be open pull request to asio project: https://github.com/chriskohlhoff/asio/pull/115 which seems to deal with asio/openssl 1.1 compatibility.

What would be the procedure with this:
- Upgrade asio code embedded in galera sources to contain fixes, or
- Wait until the fix is done in libasio-dev debian package?

**Comment by ottok** [comment]
This is still in an unconfirmed state. OpenSSL 1.1.0 has not yet entered Debian unstable (it is only in experimental): https://packages.debian.org/search?keywords=openssl&searchon=names&suite=all&section=all

**Comment by ottok** [comment]
Status update: to my knowledge libasio-dev in Debian is still incompatible with OpenSSL 1.1.

https://github.com/chriskohlhoff/asio/pull/115 was merged in late August, but the release notes at http://think-async.com/Asio/Download do not contain any dates, so I don't know when the latest release was made and if the OpenSSL 1.1 fix as been included in a stable release of Asio or not.

libasio-devel in Debian is version 1.10.8 and seems to have been uploaded to Debian on October 3rd.

**Comment by ottok** [comment]
In Debian sid (unstable) currently the versions are ASIO 1.10.8-1 and OpenSSL 1.1.0b, but Galera does not seem to build correctly: https://buildd.debian.org/status/fetch.php?pkg=galera-3&arch=amd64&ver=25.3.19-1&stamp=1478816233

**Comment by temeo** [comment]
The reason is that SSL_R_SHORT_READ is not defined in OpenSSL 1.1.0b.

**Comment by ottok** [comment]
Applied in https://github.com/ottok/galera-3/commit/34ffcd8b84d7f322b516b7e5de97daf0e4647e2b and I can confirm that the build now passed on my test machines. Will upload to Debian soon.
