### ISSUE TITLE
compiling with clang-3.8.0 causes compile error

### ISSUE THREAD

**Issue by grooverdan** [codership/galera#412]
[17:33 dan ~/repos/galera]$ clang --version
clang version 3.8.0 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
[17:33 dan ~/repos/galera]$ clang++ --version
clang version 3.8.0 (tags/RELEASE_380/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
[17:32 dan ~/repos/galera]$ export CXX=clang++
[17:32 dan ~/repos/galera]$ export CC=clang
[17:32 dan ~/repos/galera]$ scons -j 4    

<pre>
In file included from galera/src/certification.hpp:8:
galera/src/trx_handle.hpp:544:50: error: all paths through this function will call itself [-Werror,-Winfinite-recursion]
        const WriteSetOut& write_set_out() const { return write_set_out(); }
</pre>

**Comment by grooverdan** [comment]
example build failure: https://travis-ci.org/codership/galera/jobs/143262249

**Comment by ayurchen** [comment]
Dan, is clang 3.8.0 the one that fixed ABI incompatibility with GCC-5.x ?

**Comment by grooverdan** [comment]
Sorry, I don't know about any ABI incompatibility.

**Comment by ayurchen** [comment]
https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-3.6/+bug/1488254 - this makes it impossible to build Galera with clang with system boost libs built by GCC. So I just wanted to know if I could just test it with 3.8 without rebuilding boost.

**Comment by grooverdan** [comment]
I tested clang-3.8.0 compiled galera with MariaDB-10.1.16 (MariaDB repo) on ubuntu-16.04 which is compiled with gcc-5.3.1 (http://buildbot.askmonty.org/buildbot/builders/kvm-deb-xenial-amd64/builds/239/steps/compile/logs/stdio) and this worked without any trouble at all (ran sysbench through the cluster).

**Comment by philip-galera** [comment]
A fix has been committed and will be released at our next release.
