### ISSUE TITLE
Shutdown crashes node if the node started with `gcs.max_packet_size=2`

### ISSUE THREAD

**Issue by rameshvs02** [codership/galera#414]
Shutdown crashes node if the node started with `gcs.max_packet_size=2`

GDB info
{code}
(gdb) bt
+bt
#0  0x00007f1aa0841741 in pthread_kill () from /lib64/libpthread.so.0
#1  0x000000000067b1ec in handle_fatal_signal (sig=11) at /home/galera/mysql-wsrep-5.6.30-25.15/sql/signal_handler.cc:230
#2  <signal handler called>
#3  0x00007f1a9f48bd28 in _int_free () from /lib64/libc.so.6
#4  0x00007f1a9df342d8 in gcs_core_destroy (core=0x2d25e60) at gcs/src/gcs_core.cpp:1214
#5  0x00007f1a9df3bdcc in gcs_destroy (conn=0x2d25c70) at gcs/src/gcs.cpp:1469
#6  0x00007f1a9df9772b in ~Gcs (this=0x2d1e7f8, __in_chrg=<optimized out>) at galera/src/galera_gcs.hpp:93
#7  galera::ReplicatorSMM::~ReplicatorSMM (this=0x2d1e2f0, __in_chrg=<optimized out>) at galera/src/replicator_smm.cpp:263
#8  0x00007f1a9df97b89 in galera::ReplicatorSMM::~ReplicatorSMM (this=0x2d1e2f0, __in_chrg=<optimized out>) at galera/src/replicator_smm.cpp:282
#9  0x00007f1a9dfa2696 in galera_tear_down (gh=0x2ce9cc0) at galera/src/wsrep_provider.cpp:98
#10 0x0000000000b7fc3f in wsrep_unload (hptr=0x2ce9cc0) at /home/galera/mysql-wsrep-5.6.30-25.15/wsrep/wsrep_loader.c:197
#11 0x00000000005ac738 in wsrep_deinit () at /home/galera/mysql-wsrep-5.6.30-25.15/sql/wsrep_mysqld.cc:662
#12 0x00000000005a7bed in kill_server (sig_ptr=0x0) at /home/galera/mysql-wsrep-5.6.30-25.15/sql/mysqld.cc:1759
#13 0x00000000005a7dce in kill_server_thread (arg=<optimized out>) at /home/galera/mysql-wsrep-5.6.30-25.15/sql/mysqld.cc:1788
#14 0x00007f1aa083cdc5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007f1a9f50528d in clone () from /lib64/libc.so.6

(gdb) 
{cdoe}

How to reproduce

1) Configure two node cluster
2) Start cluster with `--wsrep_provider_options=gcs.max_packet_size=2`
3) Shutdown node2 

PS : This crash is happening only with first shutdown after installing system tables.

**Comment by philip-galera** [comment]
A fix for this issue has been pushed and will appear in the next Galera release.
