### ISSUE TITLE
Document that the GCache is invalidated when a node restarts

### ISSUE THREAD

**Issue by GeoffMontee** [codership/galera#431]
The documentation has a good explanation of the GCache here:

http://galeracluster.com/documentation-webpages/statetransfer.html#write-set-cache-gcache

But it doesn't explain that a node's GCache is invalidated when the node restarts. That would be helpful to know for users who might expect that nodes will be able to IST after a full cluster restart. In reality, if any nodes are missing transactions after a full cluster restart, an IST will not be available, and they will have to receive an SST. (This is related to issue #344.)

**Comment by philip-galera** [comment]
I have added some text to statetransfer.html, which will become visible on our web site shortly.
