### ISSUE TITLE
Unable to pass the Galera unit tests on several systems

### ISSUE THREAD

**Issue by sysprg** [codership/galera#432]
Recently we unable to pass the Galera unit tests on several systems:
- debian-wheezy-x64 (https://wiki.debian.org/DebianWheezy);
- ubuntu-wily-x64 (http://old-releases.ubuntu.com/releases/15.10/);
- debian-jessie-x64 with AddressSanitizer (https://www.debian.org/releases/jessie/ + https://en.wikipedia.org/wiki/AddressSanitizer);
- centos6-32 (https://wiki.centos.org/Manuals/ReleaseNotes/CentOS6.8);

The following error messages often appears in many configurations:

```
07:03:31 94%: Checks: 79, Failures: 0, Errors: 4
07:03:31 gcomm/test/check_util.cpp:170:E:test_protonet:test_protonet:0: (after this point) Test timeout expired
07:03:31 gcomm/test/check_gmcast.cpp:240:E:test_gmcast_w_user_messages:test_gmcast_w_user_messages:0: (after this point) Test timeout expired
07:03:31 gcomm/test/check_gmcast.cpp:294:E:test_gmcast_forget:test_gmcast_forget:0: (after this point) Test timeout expired
07:03:31 gcomm/test/check_pc.cpp:1427:E:test_pc_transport:test_pc_transport:0: (after this point) Test timeout expired
07:03:31 scons: *** [gcomm/test/gcomm_check.passed] Error 1
```

**Comment by philip-galera** [comment]
a Scons option, deterministic_tests=1 can now be used to bypass all non-deterministic tests.
