### ISSUE TITLE
garbd should not receive traffic

### ISSUE THREAD

**Issue by jesusch** [codership/galera#442]
it would be great in terms of traffic control when arbitrator would not receive traffic but only act as quorum
In case it will be used for backup it anyhow has to request an SST from another donor, or?

**Comment by ajaajalee** [comment]
I also would like to consider this. although garbd don't have data, all node's traffic receive.
beacuse this cause terrible traffic to garbd node, performance very bad.

**Comment by jesusch** [comment]
also in terms of security it would make a great benefit. currently all traffic towards garbd needs to be secured either by using SSL or by some VPN. It would be great to have only a qurom device with much less security considerations

**Comment by ayurchen** [comment]
Unfortunately, the current message ordering protocol requires arbitrator to see all messages. There is a benefit for that however: garbd can serve as a message relay between the nodes. So not all is lost ;)
