### ISSUE TITLE
Is a fully functional port for FreeBSD possible?

### ISSUE THREAD

**Issue by felix** [codership/galera#444]
Is there any work being done towards a fully functional port on FreeBSD? The current FreeBSD package is sitting on version 25.3.5 but does not include garbd (and other components).

On FreeBSD 11.0-RELEASE-p7, using git version 7e383f79 (and release_25.3.20.tar.gz) with the scons build I get:
```
...
Running suite(s): DataSet
100%: Checks: 1, Failures: 0, Errors: 0
Running suite(s): KeySet
100%: Checks: 1, Failures: 0, Errors: 0
Running suite(s): WriteSet
terminate called after throwing an instance of 'gu::Exception'
  what():  RecordSet checksum does not match:
computed: 82c333f3 a7631443 0465b6b1 398c3040
found:    3b12906c 3e2af41a 42abcb2b 49345ccb: 22 (Invalid argument)
         at galerautils/src/gu_rset.cpp:checksum():392
50%: Checks: 2, Failures: 0, Errors: 1
```

**Comment by philip-galera** [comment]
Hello,

Can you please try the ports scripts located at 

https://github.com/codership/freebsd-ports

Thank you.

**Comment by felix** [comment]
I was not aware of that one, thank you. Seems to work so far. When is this expected in upstream ports tree?
