### ISSUE TITLE
25.3.20 fails to build on armhf

### ISSUE THREAD

**Issue by ottok** [codership/galera#445]
While preparing an update to Debian, I noticed that the armhf build fails. All other architectures I have available for test builds passed OK:

![screenshot from 2017-01-29 14 01 35](https://cloud.githubusercontent.com/assets/668724/22403827/acb3a00a-e62b-11e6-950f-c56d84f1006c.png)
(from https://launchpad.net/~mysql-ubuntu/+archive/ubuntu/mariadb-10.1/+builds?build_text=&build_state=all)

The failure is in the test suite:
```
Running suite(s): WriteSet
g++ -o galerautils/tests/gu_thread_test.o -c -Weffc++ -Wold-style-cast -pipe -Wno-long-long -Wno-deprecated -ansi -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -g -O3 -DNDEBUG -pthread -fPIC -Wall -Wextra -Wno-unused-parameter -Werror -pedantic -Wdate-time -D_FORTIFY_SOURCE=2 -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_SYSTEM_ASIO -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -I. -Igalerautils/src galerautils/tests/gu_thread_test.cpp
50%: Checks: 2, Failures: 0, Errors: 1
galera/tests/write_set_ng_check.cpp:246:E:WriteSet:ver3_basic:0: (after this point) Received signal 7 (Bus error)
```

Full log:
https://launchpadlibrarian.net/304329684/buildlog_ubuntu-zesty-armhf.galera-3_25.3.20-1~zesty1~1485685019.0406e09_BUILDING.txt.gz

This stops me from uploading it into Debina. I would prefer a patch that can be applied against https://anonscm.debian.org/git/pkg-mysql/galera-3.git/ (example of a previous debian/patches https://anonscm.debian.org/git/pkg-mysql/galera-3.git/tree/debian/patches/fix-openssl-short-read.patch?id=1e60d2b56d4e4673bee58af79a96683284ef18e3)

**Comment by ayurchen** [comment]
Otto, is this a repeatable failure? I can't reproduce this on "linux armv7l 32bit".
The thing is that there have been no changes to write_set_ng unit since 3.19. Bus error in this case may mean running out of disk space (it is normal for mmap to overprovision memory  which may be later inaccessible)

**Comment by ottok** [comment]
I just triggered a rebuild on Launchpad and it failed again.

**Comment by ottok** [comment]
If I remember correctly, you can get very cheap access to a armhf instance here: https://www.scaleway.com/

**Comment by ayurchen** [comment]
That's what I did and the build passes for me. Unless the problem is in "zesty". Scaleway is not offering zesty yet.

**Comment by ottok** [comment]
I built on Launchpad on Xenial and the same happened again: https://launchpad.net/~mysql-ubuntu/+archive/ubuntu/mariadb-10.1/+build/11940927/+files/buildlog_ubuntu-xenial-armhf.galera-3_25.3.20-1~xenial1~1485777588.0406e09_BUILDING.txt.gz

I also built on Trusty, where now both armhf (https://launchpad.net/~mysql-ubuntu/+archive/ubuntu/mariadb-10.1/+build/11940971/+files/buildlog_ubuntu-trusty-armhf.galera-3_25.3.20-1~trusty1~1485779598.0406e09_BUILDING.txt.gz) and i386 fail (https://launchpad.net/~mysql-ubuntu/+archive/ubuntu/mariadb-10.1/+build/11940972/+files/buildlog_ubuntu-trusty-i386.galera-3_25.3.20-1~trusty1~1485779598.0406e09_BUILDING.txt.gz)

It could be something Launchpad-specific that causes the bug. But that is still a problem, because all of Ubuntu is built on the Launchpad infrastructure, and the package will not enter Ubuntu unless it builds on Launchpad.

By the way, the development version of Ubuntu (now Zesty) is 99% the same as the development version of Debina (Sid), so you could try Sid on Scaleway.

**Comment by ayurchen** [comment]
Otto,
I think my initial suspicion about the disk space is correct:
>   what():  Requested size 134219044 for './ist_check.cache' exceeds available storage space 22097920: 28 (No space left on device)

I'll try to come up with some possibly configurable solution.
Could you check if 3.19 build fails in the same way now? Just to confirm the suspicion.

**Comment by ottok** [comment]
Fixed in https://anonscm.debian.org/git/pkg-mysql/galera-3.git/commit/?id=d65cbe441a82a1828719628dcbbcd956a50c5e27

**Comment by ayurchen** [comment]
Hi Otto! This is the patch (against https://anonscm.debian.org/git/pkg-mysql/galera-3.git/) we are going to use in the the next release. Could you give it a try? Originally the patch requires setting CPPFLAGS, but for your convenience, I made it default. Thanks!
[aligned_access.diff.txt](https://github.com/codership/galera/files/892736/aligned_access.diff.txt)

**Comment by ottok** [comment]
Tested with latest 25.3.22 and all builds are OK
![screenshot from 2017-11-21 12-37-27](https://user-images.githubusercontent.com/668724/33070601-372262d4-cec1-11e7-972f-2c0f140dab3b.png)

This issue can be closed now.

**Comment by ottok** [comment]
Build logs for latest upload to Debian are all green as well (for all official Debian platforms): https://buildd.debian.org/status/package.php?p=galera-3
