### ISSUE TITLE
Galera does not consider umask when creating gcache files

### ISSUE THREAD

**Issue by shinguz** [codership/galera#449]
A customer noted that Galera does not consider umask when creating the galera cache files on node start.
He mentioned that they set explicitly umask in the way that the backup user (!= mysql) can read all galera/mysql files and complained that his umask setting is not considered.

**Comment by shinguz** [comment]
Moved to ZenDesk.

**Comment by ayurchen** [comment]
fixed in cbe62f4862e1025a94c79e8e4008685eae02fee4
