### ISSUE TITLE
"repl.commit_order=2" don't work as expected

### ISSUE THREAD

**Issue by kakuka4430** [codership/galera#452]
We understand "repl.commit_order=2" allows out of order committing only for local transactions.
So we check the behavior of this variable by two investigation.

#### [ investigation_1 ]

When large transaction is being applied from other node, we issue local small transaction 
in repl.commit_order=2 mode node. 

#### [ investigation_1 result ]

local small transaction is commited in out of order manner.

#### [ investigation_2 ]

The first node will also execute smaller transactions in parallel with the large one.
And we also issue local small transaction in repl.commit_order=2 mode node. 

#### [ investigation_2 result ]

In this case, the other transactions make the problem - out of order for local commits stops working 
on second node, apparently now blocked by the other small trx replicated in parallel. 

Above behavior is different from what we expect. 
This is specifications ?

[investigation_1_result.txt](https://github.com/codership/galera/files/775770/investigation_1_result.txt)
[investigation_2_result.txt](https://github.com/codership/galera/files/775769/investigation_2_result.txt)

**Comment by ayurchen** [comment]
Hello.
  1. please note that any other settings but repl.commit_order=3 are unsupported, purely experimental and thus have no specification. It works as it works ;)
  2. repl.commit_order=2 makes sense/difference only in master-slave setup, and only on the master node. All slave events are committed in-order, so this breaks overall OOO commiting
