### ISSUE TITLE
gcc-7 compile errors - -Werror=implicit-fallthrough=

### ISSUE THREAD

**Issue by grooverdan** [codership/galera#459]
I installed gcc-7 on ubuntu-16.04 with

<pre>
sudo -E add-apt-repository -y ppa:ubuntu-toolchain-r/test &&                     sed -e 's/xenial/zesty/g' /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-xenial.list > /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-zesty.list &&                     apt-get update && apt-get install -y gcc-7 g++-7

export CC=gcc-7
export CXX=g++-7
export 'CFLAGS=-m64 -O3 -g -mtune=native'
scons ...
</pre>

<pre>
09:28:46 galerautils/src/gu_mmh3.h: In function 'void _mmh3_128_tail(const uint8_t*, size_t, uint64_t, uint64_t, uint64_t*)':
09:28:46 galerautils/src/gu_mmh3.h:187:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
09:28:46      case 15: k2 ^= ((uint64_t)tail[14]) << 48;
09:28:46               ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
09:28:46 galerautils/src/gu_mmh3.h:188:5: note: here
09:28:46      case 14: k2 ^= ((uint64_t)tail[13]) << 40;
09:28:46      ^~~~
09:28:46 galerautils/src/gu_mmh3.h:188:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
....
</pre>

A <code>// fallthough</code> comment prior the the following case statement is sufficient to avoid this warning

**Comment by ayurchen** [comment]
> A // fallthough comment prior the the following case statement is sufficient to avoid this warning

doesn't seem to work for me (gcc version 7.0.1 20170322). Let's wait till this thing graduates from experimental

**Comment by grooverdan** [comment]
I did misspell fallth[r]ough it seems

**Comment by ayurchen** [comment]
Nah, I tried all sorts of spelling ;)

**Comment by grooverdan** [comment]
fixed in https://github.com/codership/galera/commit/d127ab9fc04e33889204fb162e943a2512e6c977
