### ISSUE TITLE
Arch linux - can't compile release 25.3.21 

### ISSUE THREAD

**Issue by Saloshp** [codership/galera#475]
Here is the compile log:

scons: Reading SConscript files ...
Host: linux x86_64 64bit
Signature: version: 3.21, revision: XXXX
Checking for C library pthread... yes
Checking for C library rt... yes
Checking for C header file sys/epoll.h... yes
Checking for C header file byteswap.h... yes
Checking for C header file endian.h... yes
Checking for C header file execinfo.h... yes
Checking for C++ header file boost/shared_ptr.hpp... yes
Checking for C++ header file unordered_map... no
Checking for C++ header file tr1/unordered_map... yes
Checking for C++ header file boost/program_options.hpp... yes
Checking for C++ header file asio.hpp... yes
Checking ASIO version (> 1.10.1) ... yes
Checking for C++ header file asio/ssl.hpp... yes
Checking for C library ssl... yes
Checking for C library crypto... yes
Checking for C header file check.h... yes
Checking for C library check... yes
Checking for C library m... yes
Checking for C library subunit... no
Checking for C library rt... yes
-std=c99 -fno-strict-aliasing -pipe 
 -g -O3 -DNDEBUG -m64 -pthread -fPIC -Wall -Wextra -Wno-unused-parameter -Werror 
 -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -DGCS_USE_GCOMM -DGALERA_LOG_H_ENABLE_CXX -Wno-variadic-macros -Wno-old-style-cast -Wno-missing-field-initializers -Wno-effc++
-Weffc++ -Wold-style-cast -pipe -Wno-long-long -Wno-deprecated -ansi 
scons: done reading SConscript files.
scons: Building targets ...
g++ -o galera/src/certification.o -c -Weffc++ -Wold-style-cast -pipe -Wno-long-long -Wno-deprecated -ansi -g -O3 -DNDEBUG -m64 -pthread -fPIC -Wall -Wextra -Wno-unused-parameter -Werror -pedantic -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -I. -Icommon -Igalerautils/src -Igcache/src -Igcs/src galera/src/certification.cpp
In file included from galerautils/src/gu_hash.h:30:0,
                 from galera/src/key_os.hpp:10,
                 from galera/src/write_set.hpp:9,
                 from galera/src/trx_handle.hpp:9,
                 from galera/src/certification.hpp:8,
                 from galera/src/certification.cpp:5:
galerautils/src/gu_mmh3.h: In function 'void _mmh3_128_tail(const uint8_t*, size_t, uint64_t, uint64_t, uint64_t*)':
galerautils/src/gu_mmh3.h:187:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case 15: k2 ^= ((uint64_t)tail[14]) << 48;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:188:5: note: here
     case 14: k2 ^= ((uint64_t)tail[13]) << 40;
     ^~~~
galerautils/src/gu_mmh3.h:188:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case 14: k2 ^= ((uint64_t)tail[13]) << 40;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:189:5: note: here
     case 13: k2 ^= ((uint64_t)tail[12]) << 32;
     ^~~~
galerautils/src/gu_mmh3.h:189:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case 13: k2 ^= ((uint64_t)tail[12]) << 32;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:190:5: note: here
     case 12: k2 ^= ((uint64_t)tail[11]) << 24;
     ^~~~
galerautils/src/gu_mmh3.h:190:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case 12: k2 ^= ((uint64_t)tail[11]) << 24;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:191:5: note: here
     case 11: k2 ^= ((uint64_t)tail[10]) << 16;
     ^~~~
galerautils/src/gu_mmh3.h:191:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case 11: k2 ^= ((uint64_t)tail[10]) << 16;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:192:5: note: here
     case 10: k2 ^= ((uint64_t)tail[ 9]) << 8;
     ^~~~
galerautils/src/gu_mmh3.h:192:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case 10: k2 ^= ((uint64_t)tail[ 9]) << 8;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:193:5: note: here
     case  9: k2 ^= ((uint64_t)tail[ 8]) << 0;
     ^~~~
galerautils/src/gu_mmh3.h:198:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  8: k1 ^= ((uint64_t)tail[ 7]) << 56;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:199:5: note: here
     case  7: k1 ^= ((uint64_t)tail[ 6]) << 48;
     ^~~~
galerautils/src/gu_mmh3.h:199:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  7: k1 ^= ((uint64_t)tail[ 6]) << 48;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:200:5: note: here
     case  6: k1 ^= ((uint64_t)tail[ 5]) << 40;
     ^~~~
galerautils/src/gu_mmh3.h:200:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  6: k1 ^= ((uint64_t)tail[ 5]) << 40;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:201:5: note: here
     case  5: k1 ^= ((uint64_t)tail[ 4]) << 32;
     ^~~~
galerautils/src/gu_mmh3.h:201:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  5: k1 ^= ((uint64_t)tail[ 4]) << 32;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:202:5: note: here
     case  4: k1 ^= ((uint64_t)tail[ 3]) << 24;
     ^~~~
galerautils/src/gu_mmh3.h:202:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  4: k1 ^= ((uint64_t)tail[ 3]) << 24;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:203:5: note: here
     case  3: k1 ^= ((uint64_t)tail[ 2]) << 16;
     ^~~~
galerautils/src/gu_mmh3.h:203:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  3: k1 ^= ((uint64_t)tail[ 2]) << 16;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:204:5: note: here
     case  2: k1 ^= ((uint64_t)tail[ 1]) << 8;
     ^~~~
galerautils/src/gu_mmh3.h:204:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
     case  2: k1 ^= ((uint64_t)tail[ 1]) << 8;
              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
galerautils/src/gu_mmh3.h:205:5: note: here
     case  1: k1 ^= ((uint64_t)tail[ 0]) << 0;
     ^~~~
In file included from galera/src/write_set_ng.hpp:18:0,
                 from galera/src/trx_handle.hpp:14,
                 from galera/src/certification.hpp:8,
                 from galera/src/certification.cpp:5:
galera/src/key_set.hpp: In member function 'bool galera::KeySet::KeyPart::matches(const galera::KeySet::KeyPart&) const':
galera/src/key_set.hpp:172:21: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 ret = (lhs[1] == rhs[1]);
                 ~~~~^~~~~~~~~~~~~~~~~~~~
galera/src/key_set.hpp:176:13: note: here
             case FLAT8:
             ^~~~
cc1plus: all warnings being treated as errors
scons: *** [galera/src/certification.o] Error 1
scons: building terminated because of errors.


Other info:

uname -a
Linux localhost 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux

**Comment by vasild** [comment]
Hello,

This is a compiler warning turned into an error. Newer compiler versions add new warnings and become more strict and sometimes get us in surprise. In this case the code is fine and the warning does not designate a real problem.

Which compiler version are you using? GCC 7?

You may workaround this by adding -Wno-implicit-fallthrough to the compiler flags (something like CXXFLAGS=-Wno-implicit-fallthrough scons ...) or by using an older compiler version.

We will try to fix this before the next version in the code (by adding the now-required /* fallthrough */ comments).

**Comment by Saloshp** [comment]
I have tried your suggestion, no luck:

`# CXXFLAGS=-Wno-implicit-fallthrough scons`

scons: Reading SConscript files ...
Host: linux x86_64 64bit
Signature: version: 3.21, revision: XXXX
Checking for C library pthread... (cached) yes
Checking for C library rt... (cached) yes
Checking for C header file sys/epoll.h... (cached) yes
Checking for C header file byteswap.h... (cached) yes
Checking for C header file endian.h... (cached) yes
Checking for C header file execinfo.h... (cached) yes
Checking for C++ header file boost/shared_ptr.hpp... (cached) yes
Checking for C++ header file unordered_map... (cached) no
Checking for C++ header file tr1/unordered_map... (cached) yes
Checking for C++ header file boost/program_options.hpp... (cached) yes
Checking for C++ header file asio.hpp... (cached) yes
Checking ASIO version (> 1.10.1) ... (cached) yes
Checking for C++ header file asio/ssl.hpp... (cached) yes
Checking for C library ssl... (cached) yes
Checking for C library crypto... (cached) yes
Checking for C header file check.h... (cached) yes
Checking for C library check... (cached) yes
Checking for C library m... (cached) yes
Checking for C library subunit... (cached) no
Checking for C library rt... (cached) yes
-std=c99 -fno-strict-aliasing -pipe 
 -g -O3 -DNDEBUG -m64 -pthread -fPIC -Wall -Wextra -Wno-unused-parameter -Werror 
 -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -DGCS_USE_GCOMM -DGALERA_LOG_H_ENABLE_CXX -Wno-variadic-macros -Wno-old-style-cast -Wno-missing-field-initializers -Wno-effc++
-Weffc++ -Wold-style-cast -pipe -Wno-long-long -Wno-deprecated -ansi -Wno-implicit-fallthrough
scons: done reading SConscript files.
scons: Building targets ...
gcc -o galerautils/src/gu_dbug.os -c -std=c99 -fno-strict-aliasing -pipe -g -O3 -DNDEBUG -m64 -pthread -fPIC -Wall -Wextra -Wno-unused-parameter -Werror -pedantic -fPIC -D_XOPEN_SOURCE=600 -DHAVE_COMMON_H -DGALERA_USE_GU_NETWORK -DHAVE_BYTESWAP_H -DHAVE_ENDIAN_H -DHAVE_EXECINFO_H -DHAVE_BOOST_SHARED_PTR_HPP -DHAVE_TR1_UNORDERED_MAP -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG=1 -DHAVE_ASIO_HPP -DHAVE_ASIO_SSL_HPP -I. galerautils/src/gu_dbug.c
galerautils/src/gu_dbug.c: In function '_gu_db_push_':
galerautils/src/gu_dbug.c:708:26: error: this statement may fall through [-Werror=implicit-fallthrough=]
      _gu_db_stack->flags |= FLUSH_ON_WRITE;
                          ^
galerautils/src/gu_dbug.c:709:2: note: here
  case 'a':
  ^~~~
cc1: all warnings being treated as errors
scons: *** [galerautils/src/gu_dbug.os] Error 1
scons: building terminated because of errors.

P.S the information you requested:
gcc (GCC) 7.1.1 20170630

**Comment by vasild** [comment]
I assumed this is only present in .cc files (CXXFLAGS), but it also is present in gu_dbug.c which would be compiled using CFLAGS, so:

CFLAGS=-Wno-implicit-fallthrough CXXFLAGS=-Wno-implicit-fallthrough scons ...

**Comment by Saloshp** [comment]
I can confirm that:
`# CFLAGS=-Wno-implicit-fallthrough CXXFLAGS=-Wno-implicit-fallthrough scons`
worked, thank you very much.

**Comment by darix** [comment]
wouldn't the proper fix be to actually handle the default case instead of just turning off the warning?

IMHO this bug should be reopened

**Comment by vasild** [comment]
@darix sure. I pointed the above workaround because it does not involve editing source code.

**Comment by darix** [comment]
We applied the same workaround to the opensuse package as well. but either the galera build system should set the flag or fix the code. it shouldnt be something that each user has to do.

**Comment by vasild** [comment]
Right, it is just that we haven't yet caught up with the latest and the greatest GCC...

**Comment by darix** [comment]
if you want i can help you setting up a test package on the [OBS](https://build.opensuse.org/) and hook up github to the OBS. then you would notice such things quickly :D

**Comment by vasild** [comment]
That would be great!

**Comment by darix** [comment]
just hit me on on freenode or oftc tomorrow.
