### ISSUE TITLE
Implement new status variable:  wsrep_cluster_weight

### ISSUE THREAD

**Issue by claudionanni** [codership/galera#501]
Currently it is possible to know the size of the cluster via the status variable: **wsrep_cluster_size**.
Since each node can have an arbitrary weight it is not possible to know the current total weight of the Primary Component of the cluster.
I think it could be useful to know the current weight of the Primary Component in case new nodes need to be added and/or a cluster rebalancing is needed by changing a node weight.
It could also be useful for monitoring.
Of course that's a dynamic status variable which does not tell anything about the planned cluster designated weights since nodes could be down, or not yet started.
The new variable **wsrep_cluster_weight** could be defined as the sum of the weights of the nodes belonging to the Primary Component, each node should already have such info as it is used to calculate the quorum.

**Comment by temeo** [comment]
Will be included in the next Galera release.
