### ISSUE TITLE
Build failure on Fedora 27

### ISSUE THREAD

**Issue by valeriikravchuk** [codership/galera#503]
I tried to build from the fresh clone:

[openxs@fc23 galera]$ git branch
* 3.x
[openxs@fc23 galera]$ git log -1
commit ac090bccf900c8346f2367469ac0c3ea7f1640cb (HEAD -> 3.x, tag: release_25.3.23, origin/HEAD, origin/3.x)
Author: Teemu Ollakka <teemu.ollakka@galeracluster.com>
Date:   Tue Feb 6 12:47:00 2018 +0200

    Bumped version to 25.3.23

that I've created as follows:

1032     rm -rf galera/
1033     git clone https://github.com/codership/galera.git
1034     cd git
1035     cd galera/
1036     git log -1
1037     git branch
1038     ./scripts/build.sh

on recently updated Fedora 27 with all documented dependencies installed:

[openxs@fc23 galera]$ rpm -q -a | grep devel
...
openssl-devel-1.1.0h-3.fc27.x86_64
gnutls-devel-3.5.18-2.fc27.x86_64
...
mariadb-devel-10.2.14-1.fc27.x86_64
...
boost-devel-1.64.0-5.fc27.x86_64
...
check-devel-0.11.0-3.fc27.x86_64
...

The result is the following:

[openxs@fc23 galera]$ find . -name ssl.hpp
./asio/asio/ssl.hpp
[openxs@fc23 galera]$ ./scripts/build.sh
~/git/galera ~/git/galera
~/git/galera
scons: Reading SConscript files ...
Host: linux x86_64 64bit
Signature: version: 3.23, revision: 3730
Using C compiler executable: gcc
C compiler version is: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Using C++ compiler executable: g++
C++ compiler version is: g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Checking for C library pthread... yes
Checking for C library rt... yes
Checking for C header file sys/epoll.h... yes
Checking for C header file byteswap.h... yes
Checking for C header file endian.h... yes
Checking for C header file execinfo.h... yes
Checking if compiling in C++11 mode ... no
Checking for std::tr1::array ... yes
Checking for C++ header file boost/shared_ptr.hpp... yes
Checking for std::tr1::unordered_map ... yes
Checking for C++ library boost_program_options... yes
Checking for C++ header file asio.hpp... no
Falling back to bundled asio
Checking for C++ header file asio.hpp... yes
Checking for C++ header file asio/ssl.hpp... no
SSL support required but asio/ssl.hpp was not found or not usable
check that SSL devel headers are installed and usable

Surely the library is not built.

I am not sure why it says there is a problem with asio/ssl.hpp if we clearly see it is bundled.

What is the problem here and how to resolve it?

**Comment by temeo** [comment]
File config.log or cofigure.log in build root could give some more hints. I'd suspect that bundled asio library does not cope well with openssl 1.1. Please try if installing asio-devel resolves the issue.

**Comment by valeriikravchuk** [comment]
Installing asio-devel helped:

```
[openxs@fc23 galera]$ ls -l *.so
-rwxrwxr-x. 1 openxs openxs 40147528 Apr 12 20:31 libgalera_smm.so
[openxs@fc23 galera]$ fc -l
...
998      rpm -q -a | grep asio
999      uname -a
1000     sudo dnf install asio-devel
1001     cd git/galera/
1002     ./scripts/build.sh
1003     ls -l *.so
[openxs@fc23 galera]$
```

Sorry, not sure how I missed it. Maybe because it is not mentioned in "BUILDING on CentOS/RHEL 5" section of README (that probably should be updated for CentOS/RHEL 7 at least anyway).

**Comment by valeriikravchuk** [comment]
It was mostly my fault. Installing asio-devel helped. Closing.
