### ISSUE TITLE
wsrep_cluster_weight variable documentation bug/typo

### ISSUE THREAD

**Issue by kedarvj** [codership/galera#518]
http://galeracluster.com/documentation-webpages/galerastatusvariables.html#wsrep-cluster-weight
There's documentation typo in the name of the variable; used wsrep_cluster_size instead of wsrep_cluster_weight.

![image](https://user-images.githubusercontent.com/369587/45225111-5fd14e00-b2d9-11e8-8650-63282969c76b.png)

```
SHOW STATUS LIKE 'wsrep_cluster_weight';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| wsrep_cluster_size | 3     |
+--------------------+-------+
```

**Comment by temeo** [comment]
Hi @kedarvj, thanks for the report!

The typo was fixed and new version of documentation was deployed on the website.
