### ISSUE TITLE
Cannot join a cluster anymore when using IPv6 in gmcast.listen_addr

### ISSUE THREAD

**Issue by dciabrin** [codership/galera#534]
After the new way of sanitizing ipv6 parsing/printing [1], it is now
mandatory to express IPv6 address with enclosing square brackets,
e.g.:
```
   wsrep_provider_options = gmcast.listen_addr=tcp://[fd00:50c5:8119:5564:0:ee39:f850:c5f3]:4567;
```
This has a side effect on applications that try to join a running
galera cluster. Specifically, this makes
`gcomm::AsioTcpSocket::connect(const gu::URI& uri)` fail, due to the way
it configures the source address of the socket that is created to
connect to the galera cluster.

Before the ipv6 rework [1], it was implicitly expected that the source
address (local variable `bind_ip`) always receives an IP address as
configured in the `GMCast` object [2]: But since the ipv6 rework, the
string passed as a source address may now contain brackets when an
IPv6 is used, and this is considered an invalid input when calling
`asio::ip::address::from_string()` (which internally maps to `inet_pton`).

[1] GAL-501 Improved URI parsing for IPv6 addresses, c6ada002813093ab56e387ebe237a45600bbd775
[2] From `GMCast::gmcast_connect`: "bind outgoing connections to the same address as listening."

**Comment by dciabrin** [comment]
FTR, I've tested that https://github.com/dciabrin/galera-1/commit/0f6f8aeeb09809280c956514cfd5844b8acad4f9 by deploying a 3-node galera cluster in IPv4, IPv4+TLS, IPv6 and IPv6+TLS. Connection work for all cases, and I didn't see any adverse side effect.

**Comment by ayurchen** [comment]
@dciabrin thanks for pointing this out! The fix will be available in the next release.

**Comment by dciabrin** [comment]
@ayurchen thanks for the heads up.
Is there already an estimate of when the next release (or just that fix really :P) will be available?
FTR, the reason I'm asking is that for next release of OpenStack, we planned to upgrade galera in our RDO packages from galera 25.3.16 to 25.3.23, and to workaround this IPv6 issue, we currently bind to [::], so we've lost the ability to bind to a specific NIC.
