### ISSUE TITLE
Missing tag for galera4 v26.4.3

### ISSUE THREAD

**Issue by rafariossaa** [codership/galera#556]
Hi,
  I have notice that the tag for the version 26.4.3 is missing (or the code haven't been pushed to github) but in [archive.mariadb.org](http://archive.mariadb.org/mariadb-10.4.10/galera-26.4.3/src/) it does exist.

Thanks forehand,

**Comment by temeo** [comment]
Hi,

Thanks for notifying. The tag and branch were not pushed. Pushed, so the release 26.4.3 should be in 4.x branch now.
