### ISSUE TITLE
Galera build failure with `,-D_GLIBCXX_ASSERTIONS`

### ISSUE THREAD

**Issue by temeo** [codership/galera#557]
First reported here: https://jira.mariadb.org/browse/MDEV-15389

To reproduce, run build with `CXXFLAGS="-D_GLIBCXX_ASSERTIONS" scons`.

**Comment by FaramosCZ** [comment]
Hello, what's the status of this isuue?
I see it as a closed, but without any PR or commit.

I'd like this issue to be resolved.
There is a tracker for this issue for MariaDB, Fedora and RHEL.

**Comment by temeo** [comment]
Hi,

Two commits corresponding to this issue have been pushed in the latest `release_25.3.29`:

https://github.com/codership/galera/commit/47d112023efa83990cde6d6f137db92f364232ca
https://github.com/codership/galera/commit/3752a9e340a2eb6579e37a1a0adaeb6deaecef0b

All debug builds are now compiled with `-D_GLIBCXX_ASSERTIONS` and we haven't seen any issues it lately, so it should be fixed now.

Feel free to reopen this issue or submit a new one if you still see issues with `-D_GLIBCXX_ASSERTIONS` with the latest release.
