### ISSUE TITLE
Handshake failures when using LetsEncrypt

### ISSUE THREAD

**Issue by trixpan** [codership/galera#571]
It seems like Galera struggles to use certificates like the ones issued by letsencrypt.

This is referred to in [here](https://www.linuxbabe.com/mariadb/encrypt-replication-traffic-mariadb-galera-cluster-ubuntu)

and I can also confirm seeing stuff like

`[ERROR] WSREP: handshake with remote endpoint ssl://xx.xx.xx.xx:4567 failed: asio.ssl:337047686: 'certificate verify failed' ( 337047686: 'error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed')`

When using `openssl s_client -showcerts` it seems like Galera doesn't send the certificate chain, just the leaf certificate (the final CN). 

Is there a way of configuring it to send the complete certificate?

```
2020-04-17  0:40:19 140135207557312 [Note] WSREP: wsrep_load(): loading provider library '/usr/lib64/galera/libgalera_smm.so'
2020-04-17  0:40:19 140135207557312 [Note] WSREP: wsrep_load(): Galera 25.3.28(r3875) by Codership Oy <info@codership.com> loaded successfully.
```

**Comment by trixpan** [comment]
Seems like the issue is caused by Galera not using boost's `use_certificate_chain_file`

https://github.com/codership/galera/blob/88f3e29c5d798ad72ba991493c09538abdb26a54/galerautils/src/gu_asio.cpp#L172

Note the subtle difference to:

```
    context_.set_password_callback(boost::bind(&server::get_password, this));
    context_.use_certificate_chain_file("server.pem");
    context_.use_private_key_file("server.pem", boost::asio::ssl::context::pem);
```

https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/example/cpp03/ssl/server.cpp

@temeo is this something that could be changed? It _should not introduce regressions_(:tm:)

**Comment by temeo** [comment]
Hi @trixpan 

Thanks for pointing this out! Call to `use_certificate_chain_file()` is indeed preferred as it allows using certificate chains in certificate file. I don't see any reason why this change would cause any regressions, so it should be relatively safe to make.

**Comment by trixpan** [comment]
@temeo my pleasure! I am not a CPP person and certificate chains are a bit of a nightmare subject so it took me a while to understand the issue.

Do you reckon a fix could be backported to 25.3.x by any chance? (as I am not familiar with the two different version tracks OSS Galera and Codership Oy Galera seem to adopt)

**Comment by temeo** [comment]
We will test the change and if it does not show any regressions, it should make it to the next release.

Btw, did you test if the change to `use_certificate_chain_file()` fixes the issue?

**Comment by trixpan** [comment]
@temeo apologies for the delay in replying.

No. I did not test the change fixes the issue. Planning to do this next week as I had some conflicting priorities.

**Comment by mariadb-RobSchwyzer** [comment]
Wanted to let you know a DigiCert setup is experiencing similar issues-

### Server A
```
[ERROR] WSREP: handshake with remote endpoint ssl://xxx.xxx.xxx.xxx:54114 failed: asio.ssl:336105671: 'peer did not return a certificate' ( 336105671: 'error:140890C7:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:peer did not return a certificate')
```

### Server B
```
[ERROR] WSREP: handshake with remote endpoint ssl://xxx.xxx.xxx.xxx:4567 failed: asio.ssl:336134278: 'certificate verify failed' ( 336134278: 'error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed')
```

Could this be related?

**Comment by hholzgra** [comment]
Any news / ETA on this one?

**Comment by hholzgra** [comment]
Again: any news / ETC on this one?

**Comment by trixpan** [comment]
This fix was released a while back but the GH issue wasn't closed.

https://github.com/codership/galera/commit/a3412df7c97db459a2cdea895220d78d9093fdaa

Ensure you are running a fixed version and report accordingly
