### ISSUE TITLE
Feature Request: Counter for Galera relay status

### ISSUE THREAD

**Issue by ssgoburdhun** [codership/galera#573]
Scenario:

We have a 3-node Galera cluster on MariaDB.
Normal 3-way communication:
1 <-> 2
1 <-> 3
2 <-> 3

State: Cluster is stable and behaving properly.

Case: 
- Interrupt network connection between 2 <-> 3

What happens: 
There will be at least 1 node that starts the relaying process:
```
# Node1
[Note] WSREP: (82449226, 'tcp://0.0.0.0:4567') turning message relay requesting on, nonlive peers, tcp://ip2:4567 tcp://ip3:4567 
---
# Node2
[Note] WSREP: (761f9b55, 'tcp://0.0.0.0:4567') turning message relay requesting on nonlive peers, tcp://ip1:4567 tcp://ip3:4567
---
# Node3 
Similar behaviour expected
```

Is it possible to add a status counter (show global status) so that each time a node starts the relay process that counter is incremented?

It can be a preventive method and act as a monitoring measure.

Kind Regards,
Sarvesh.

**Comment by ayurchen** [comment]
Hi,

By "starts a relay process" you mean
a) acts as a relay?
b) requests relay?

In the latter case, should this counter be cluster-wide or local to the requester?

**Comment by ssgoburdhun** [comment]
Thanks for getting back.

I mean option a) acts as a relay.

The status counter can be a boolean value ( 1: when the node starts acting as a relay )

It will be easier to also track the number of times a node acts as a relay (might pinpoint a problematic node)

Therefore, for administrative purposes it seems better having the status counter locally on the actor node.

If you have other questions, please let me know.

**Comment by ayurchen** [comment]
Perhaps there is some misunderstanding. How would a node acting as a relay help pinpoint the problematic node? Relay node is the least problematic there.

**Comment by ssgoburdhun** [comment]
There is indeed a misunderstanding here. 
Closing it.
