### ISSUE TITLE
galera-4_26.4.5-1 failed to build on riscv64

### ISSUE THREAD

**Issue by ottok** [codership/galera#576]
I noticed that the galera-4 package version 26.4.5-1 failed to migrate form Debian to Ubuntu due to a build failure on Launchpad arch riscv64:
```
50%: Checks: 2, Failures: 0, Errors: 1
galerautils/tests/gu_fifo_test.c:74:E:gu_fifo:gu_fifo_test:0: (after this point) Test timeout expired
```
https://launchpadlibrarian.net/482041187/buildlog_ubuntu-groovy-riscv64.galera-4_26.4.5-1_BUILDING.txt.gz

https://launchpad.net/ubuntu/+source/galera-4
![image](https://user-images.githubusercontent.com/668724/85952127-e43e0680-b96f-11ea-893b-dfb55fc01a7c.png)

The previous version did not fail to build, so this is a regression.
![image](https://user-images.githubusercontent.com/668724/85952141-f455e600-b96f-11ea-91ba-a8970a05a73b.png)

**Comment by ottok** [comment]
This bug still applies and has prevented 26.4.5-1 from entering the latest Ubuntu development release (to be released next month): https://launchpad.net/ubuntu/+source/galera-4

Same riscv64 issue also applies for galera-3: https://launchpad.net/ubuntu/+source/galera-3

**Comment by temeo** [comment]
@ottok would it make sense to try to increase unit test timeouts for riscv64 builds as it is done for mipsel in `debian/rules`:
```
ifeq (mipsel,$(DEB_HOST_ARCH))
        export CK_TIMEOUT_MULTIPLIER=2
endif
```
This way we could find out of the test is just slow on that platform or is there deeper problem around.

**Comment by ottok** [comment]
Thanks, I'll try this.

**Comment by ottok** [comment]
Timeout seems like the culprint. Did multiple test builds at https://launchpad.net/~otto/+archive/ubuntu/mariadb/+builds?build_text=&build_state=all and they all worked now.

**Comment by ottok** [comment]
This was indeed just a timeout issue and after triggering a couple of rebuilds it passed. All good currently at https://launchpad.net/ubuntu/+source/galera-4.

![image](https://user-images.githubusercontent.com/668724/92790638-a10f0380-f3b4-11ea-9bdb-bf792f011f6c.png)

Since the timeout seems to happen often on different platforms, I decided to apply it anyway all the time: https://salsa.debian.org/mariadb-team/galera-4/-/commit/cbd995fbb2c63a71fea3daff9f2cd9857a5feaf0
