### ISSUE TITLE
`drop trigger` not replicated

### ISSUE THREAD

**Issue by fabrykowski** [codership/galera#578]
I have set up a small cluster of three MariaDB servers synchronised via Galera.

Everything works perfectly, except for the fact that I can neither edit nor drop triggers from tables, once defined. The only way to get rid of a trigger is to drop the entire table, which – for obvious reasons – is a non-starter.

Even though my actual setup is bare-metal, I have put together an MWE running on Docker and exhibiting the same behaviour: [galera_drop_trigger_mwe](https://github.com/fabrykowski/galera_drop_trigger_mwe)

Is there anything missing from my configuration, or is this actually a bug in this constellation?

**Comment by janlindstrom** [comment]
This is clearly a bug, please fill a bug report at jira.mariadb.org

**Comment by fabrykowski** [comment]
This bug is tracked by ~~https://jira.mariadb.org/browse/MDEV-21578~~ https://jira.mariadb.org/browse/MDEV-23638.
