### ISSUE TITLE
MariaDB Galera Arbitrator failing to sync with SSL

### ISSUE THREAD

**Issue by LefterisL** [codership/galera#592]
So the scenario is this. I have already setup a 4 node MariaDB Galera cluster (10.5). I'm also adding on top a 5th Galera Arbitrator and everything syncs and connects just fine. However when I enable SSL on the cluster ( after bootstrapping it from scratch ) I'm able to sync the 4 nodes but the Arbitrator for some reason does not sync.

Interesting is that when the nodes are syncing they're outputting "connecting...ssl://172.31.0.4:4567". However when the arbitrator is trying to sync it's outputting "connecting...tcp://172.31.0.4:4567". Seems like it's trying over tcp for some reason.

It's config is this when I start it up

    address: gcomm://mariadb-galera-0:4567,mariadb-galera-1:4567,mariadb-galera-2:4567,mariadb-galera-3:4567,mariadb-galera-arb:4567

    group:   scluster

    sst:     trivial

    donor:

    options: socket.ssl_key=/etc/ssl/galera/server-key.pem;socket.ssl_cert=/etc/ssl/galera/server-cert.pem;socket.ssl_ca=/etc/ssl/galera/ca-cert.pem;socket.ssl_cipher=AES128-SHA; gcs.fc_limit=9999999; gcs.fc_factor=1.0; gcs.fc_master_slave=yes

    cfg:

    log:

It doesn't give me an ssl or cert error just timing out

`INFO: (8bef8261-9d27, 'tcp://0.0.0.0:4567') connection to peer 00000000-0000 with addr tcp://172.31.0.4:4567 timed out, no messages seen in PT3S, socket stats: rtt: 39 rttvar: 19 rto: 200000 lost: 0 last_data_recv: 3500 cwnd: 10 last_queued_since: 3499991400 last_delivered_since: 3499991400 send_queue_length: 0 send_queue_bytes: 0`

The pem files are exactly the same that I'm using across all nodes + the arbitrator.

I read in the documentation that I need to specify the cipher otherwise I'll be getting an error. I tried AES128-SHA and AES128-SHA256 and not declaring it at all but still timing out.

Below is the wsrep provider options from the phpmyadmin from one of the nodes. The cipher seems empty but then again why is the arbitrator trying to connect to "tcp://" and not "ssl://" like the others ? enter image description here

![image](https://user-images.githubusercontent.com/5937357/118977777-379db680-b97f-11eb-9a4d-1c20d90fb794.png)

Thank you for helping

**Comment by mupkw** [comment]
Hi,

I've had the same problem in a 2 node MariaDB (10.5.10) + 1 arbitrator (garbd --version INFO: 26.4.8.r) cluster.

As all worked fine without SSL and based on issue #495 I thought, it must be SSL and I played around with my self-generated SSL-certificates (servername in CN field, using socket.ssl_ca vs. having complete cert chain in the socket.ssl_cert file, having same/different certs on each server, activating debug infos, etc.). Nothing helped.

Then your post has born the idea, SSL might not be activated at all.
In MariaDB-docu [socket.ssl_ca](https://mariadb.com/kb/en/wsrep_provider_options/#socketssl_ca) and other socket.ssl_... parameters state, that *socket.ssl = yes* was implicated automatically, if any of the ssl parameters were used.
Galera [parameter docu](https://galeracluster.com/library/documentation/galera-parameters.html) does not list *socket.ssl*.
But nevertheless I tried `socket.ssl = yes` and now it works!
I wonder, why no documentation or tutorial mentions this.

My complete options:
`GALERA_OPTIONS="socket.ssl=yes;socket.ssl_cipher=TLSv1.3:TLSv1.2;socket.ssl_key=/etc/ssl/private/<mykey>.pem;socket.ssl_cert=/etc/ssl/certs/<mycert>.pem;socket.ssl_ca=/etc/ssl/certs/<myca>.pem"`
(whereas I gave user nobody, who starts garbd by default, read access to these files).

**Comment by LefterisL** [comment]
> Hi,
> 
> I've had the same problem in a 2 node MariaDB (10.5.10) + 1 arbitrator (garbd --version INFO: 26.4.8.r) cluster.
> 
> As all worked fine without SSL and based on issue #495 I thought, it must be SSL and I played around with my self-generated SSL-certificates (servername in CN field, using socket.ssl_ca vs. having complete cert chain in the socket.ssl_cert file, having same/different certs on each server, activating debug infos, etc.). Nothing helped.
> 
> Then your post has born the idea, SSL might not be activated at all.
> In MariaDB-docu [socket.ssl_ca](https://mariadb.com/kb/en/wsrep_provider_options/#socketssl_ca) and other socket.ssl_... parameters state, that _socket.ssl = yes_ was implicated automatically, if any of the ssl parameters were used.
> Galera [parameter docu](https://galeracluster.com/library/documentation/galera-parameters.html) does not list _socket.ssl_.
> But nevertheless I tried `socket.ssl = yes` and now it works!
> I wonder, why no documentation or tutorial mentions this.
> 
> My complete options:
> `GALERA_OPTIONS="socket.ssl=yes;socket.ssl_cipher=TLSv1.3:TLSv1.2;socket.ssl_key=/etc/ssl/private/<mykey>.pem;socket.ssl_cert=/etc/ssl/certs/<mycert>.pem;socket.ssl_ca=/etc/ssl/certs/<myca>.pem"`
> (whereas I gave user nobody, who starts garbd by default, read access to these files).

Unbelievable. It works. Appreciate it
