### ISSUE TITLE
Broken repodata for centos 5.7.37?

### ISSUE THREAD

**Issue by tdmayden** [codership/galera#619]
Hi there,

On trying to install various components from the Galera repos, yum reports that `5.7.36-25.28.el7` will be installed,  but fails when the installation starts because the repo doesn't include the 5.7.36 packages inside http://releases.galeracluster.com/mysql-wsrep-5.7/centos/7/x86_64/

Is the repodata broken?

Can you help?

Thanks!

**Comment by temeo** [comment]
Hi, 

Does clearing repo metadata help?

```
# yum clean metadata
```

**Comment by tdmayden** [comment]
Hi temeo, I'm afraid not. `yum clean all` followed by `yum install mysql-wsrep-5.7` still shows that the VM wants to install version `5.7.36-25.28.el7` which isn't available in the repo. This is a brand new instance created today, so hasn't ever tried to retrieve packages before.

**Comment by temeo** [comment]
I just tried with clean CentOS 7, `/etc/yum.repos.d/galera.repo`:
```
[galera]
name = Galera
baseurl = https://releases.galeracluster.com/galera-3/centos/7/x86_64
gpgkey = https://releases.galeracluster.com/GPG-KEY-galeracluster.com
gpgcheck = 1

[mysql-wsrep]
name = MySQL-wsrep
baseurl =  https://releases.galeracluster.com/mysql-wsrep-5.7/centos/7/x86_64
gpgkey = https://releases.galeracluster.com/GPG-KEY-galeracluster.com
gpgcheck = 1
```

The following
```
# yum install -y mysql-wsrep-5.7
# yum install -y galera-3
``` 
works for me.

**Comment by temeo** [comment]
The repository was updated today, so it is possible that the installation happened during the repo update. If the installation is in fresh VM, try
```
# yum remove -y $(rpm -qa | grep mysql-wsrep)
```
followed by
```
yum install -y mysql-wsrep-5.7
```

**Comment by tdmayden** [comment]
Hi temeo, thanks for this. Looks like the problem lies with the http:// version of the repo - when using http:// (our default) we are always returned 5.7.36 from yum, but it fails to fetch that because those packages don't exist on the repo. However when switching over to https:// we do indeed get 5.7.37 - so thanks for the heads up, but there might be a disparity between the http and https versions?

**Comment by temeo** [comment]
I tried also with http, and the 5.7.37 packages installed in the clean system fine. Could it be possible that there is some proxy in between which returns wrong repository meta data for some reason?

Using the URL with full version http://releases.galeracluster.com/mysql-wsrep-5.7.37-25.29/centos/7/x86_64/ should work around the issue.

**Comment by tdmayden** [comment]
Yeah, that's exactly the problem, we recently introduced a proxy. So sorry for the hassle, but thanks for your support!
