### ISSUE TITLE
galera-4 26.4.12 on ubuntu focal not build

### ISSUE THREAD

**Issue by andykimpe** [codership/galera#628]
this error to build please solve

<code>
wget https://github.com/codership/galera/archive/refs/tags/release_26.4.12.tar.gz -O galera-4_26.4.12.orig.tar.gz

tar -xvf galera-4_26.4.12.orig.tar.gz

cd galera-release_26.4.12

debuild
</code>

retur this error

<code>
galera-release_26.4.12/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: sys/byteorder.h: no file or folder of type
    1 | #include <sys/byteorder.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/cmTC_9f24e.dir/build.make:66 : CMakeFiles/cmTC_9f24e.dir/CheckIncludeFile.c.o] Erreur 1
</code>

**Comment by andykimpe** [comment]
ok solved for focal use with mariadb source repository


wget https://archive.mariadb.org/mariadb-10.9.3/galera-26.4.12/src/galera-26.4.12.tar.gz -O galera-4_26.4.12.orig.tar.gz



work

**Comment by temeo** [comment]
The actual error was earlier in debuild output:
```
CMake Error at wsrep/tests/CMakeLists.txt:11 (add_executable):
  Cannot find source file:

    ../src/wsrep_loader.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```
and the reason for the error is that download from github does not contain Galera repo submodules.

Self contained tarballs for Galera releases can be obtained from http://releases.galeracluster.com/, http://releases.galeracluster.com/galera-4.12/source/galera-4-26.4.12.tar.gz.
