### ISSUE TITLE
asio check in SConstruct needs updating

### ISSUE THREAD

**Issue by hydrapolic** [codership/galera#631]
Currently SConstruct mentions:
    context.Message('Checking ASIO version (>= 1.10.8 and < 1.11.0) ... ')

For in-system asio. However asio was upgraded to 1.22.1 (https://github.com/codership/galera/commit/60d5e4c6b4c65dd9da54078bddd8e198cd1de048) and later downgraded to 1.14.1 (https://github.com/codership/galera/commit/f90cad156bbe5f377c95a7a3c5ca87546664f569), so the check probably needs to be updated.

**Comment by temeo** [comment]
Is there any reason to stick with SCons builds anymore? CMake based builds have been in place for over two years now.

**Comment by hydrapolic** [comment]
Sorry I haven't noticed the transition to cmake, I'll try to update our ebuild to cmake, thanks!
