### ISSUE TITLE
Post-builds success depends on build environment (TLS timeout case)

### ISSUE THREAD

**Issue by ottok** [codership/galera#647]
Debian has a system checking for build reproducibility. Currently it shows that latest version of Galera does not build if the build environment is slightly different.

See https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/galera-4.html

![image](https://github.com/codership/galera/assets/668724/cf439869-c6c5-4ffc-8f8d-73450ebc4c9f)

The difference between build 1 and build 2 is visible in https://tests.reproducible-builds.org/debian/logdiffs/unstable/amd64/galera-4_26.4.16-1.diff.gz

The purpose of the post-build test is to catch code regressions. Thus it should not have the behavior that is passes on one build and fails on another build with slightly different environment (build dependencies are still the same, but e.g. build time or path might have changed). Hence I would classify this as a bug that the test is not 'stable' enough.

Looking at the output the issue has something to do with TLS connections timing out. Could perhaps be something as simple as TLS certificates being expired / not valid in future (if the source code has fixed certificates somewhere).

**Comment by temeo** [comment]
The probable reason for test failures is indeed certificates which expire in Jan  6 10:30:06 2024 GMT,
the build system current time is Wed Oct 23 08:57:16 +14 2024.

So the tests which require certificates need to be fixed to generate the certificates automatically.

**Comment by temeo** [comment]
Fixed in Galera 26.4.17.

**Comment by ottok** [comment]
For the record, latest Galera 26.4.18 in Debian builds pass on all [reproducible build builders](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/galera-4.html).

![image](https://github.com/codership/galera/assets/668724/5959818d-c955-489d-b616-2a624df74a0a)
